### ISSUE TITLE
Test failed in dev branch.

### ISSUE THREAD

**Issue by kroniak** [tmenier/Flurl#109]
In last build on NET CORE 1.0.0:

https://ci.appveyor.com/project/kroniak/flurl/build/1.0.0-dev-26

Failed : Flurl.Test.Http.RealHttpTests.can_cancel_request
  Expected: Flurl.Http.FlurlHttpException
  But was:  System.Threading.Tasks.TaskCanceledException: A task was canceled.

**Comment by kroniak** [comment]
I see that test are failed after appveyor was updating NET CLI  tools to 1.0.0

https://ci.appveyor.com/project/kroniak/flurl/build/1.0.0-dev-25
and 
https://ci.appveyor.com/project/kroniak/flurl/build/1.0.0-master-26-gxfikmdx  

In my environment I have some error on NET CLI tools 1.0.0

**Comment by kroniak** [comment]
And I see that github disconnect from AppVeyor. Please check it.

**Comment by tmenier** [comment]
There were 2 webhook timeouts on 6/30 but they seem to have disconnected. I'll look at the failing test but I don't believe there's a connection problem between GitHub and AppVeyor anymore.

**Comment by kroniak** [comment]
Test is failed on my computer with core 1.0.0 and in AppVeyor 
https://ci.appveyor.com/project/kroniak/flurl/build/1.0.0-dev-31

**Comment by kroniak** [comment]
Fix by https://github.com/tmenier/Flurl/commit/6ff642fedec13833f9926016bbfa358012e66d16

**Comment by tmenier** [comment]
@kroniak I see your change does cause the test to pass but it should absolutely not be necessary. I very strongly suspect the issue is with the NUnit test runner. I'm going to revert your change and update the runner, and if that doesn't work I'll just have it ignore the test in .NET Core. The problem is definitely not with Flurl or .NET Core.

**Comment by tmenier** [comment]
I thought the NUnit test runner was the problem but I was wrong - it was [this bit](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L372-L376) in the .NET Core version of HttpClient, which I'm guessing is different than the 4.5 version. It basically discards the thrown FlurlHttpException and throws an OperationCanceledException instead. Easiest way to avoid it was to not have FlurlHttpException inherit from HttpRequestException, which is of no value anyway.

I reverted your changes since they aren't necessary, and I prefer to keep error-handling details in the MessageHandler as much as possible. Thanks though - your fix helped steer me in the right direction.
