### ISSUE TITLE
SetQueryParams only supports anonymous type

### ISSUE THREAD

**Issue by tylerlong** [tmenier/Flurl#116]
Sample code:

```cs
using System;
using Flurl;
using Flurl.Http;

namespace ConsoleApplication
{
    public class MyParams
    {
        public string q;
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            var response = "https://github.com/search".SetQueryParams(new  { q = "test" }).GetAsync().Result;
            Console.WriteLine(response.RequestMessage.RequestUri.AbsoluteUri);
            var response2 = "https://github.com/search".SetQueryParams(new MyParams { q = "test" }).GetAsync().Result;
            Console.WriteLine(response2.RequestMessage.RequestUri.AbsoluteUri);
        }
    }
}
```

output:

```
https://github.com/search?q=test
https://github.com/search
```

I don't understand, why `new  { q = "test" }` works while `new MyParams { q = "test" }` doesn't work.

**Comment by tylerlong** [comment]
OK, I've found the root cause:

https://github.com/tmenier/Flurl/blob/840a690f13b66e4b30ecc02d2560481287ba5908/src/Flurl.Shared/Util/CommonExtensions.cs#L55

```cs
private static IEnumerable<KeyValuePair<string, object>> ObjectToKV(object obj) {
    return from prop in obj.GetType().GetProperties() 
        let val = prop.GetValue(obj, null) 
        select new KeyValuePair<string, object>(prop.Name, val);
}
```

So apparently only **properties** are supported, fields are not supported.

Is this by design or bug?

**Comment by tmenier** [comment]
That is the cause and it's by design. Just change it to this:
```c#
public class MyParams
{
    public string q { get; set; }
}
```
This is a best practice and almost all reflectionary tools/libraries in the .NET ecosystem ignore public fields. Reflecting on public fields is not a change I'll consider.

http://programmers.stackexchange.com/questions/120497/why-are-public-and-private-accessors-considered-good-practice
http://csharpindepth.com/Articles/Chapter8/PropertiesMatter.aspx
https://blogs.msdn.microsoft.com/vbteam/2009/09/04/properties-vs-fields-why-does-it-matter-jonathan-aneja/
