### ISSUE TITLE
HTTP Cache, etag, etc

### ISSUE THREAD

**Issue by andresmoschini** [tmenier/Flurl#137]
Hi @tmenier, I would ask you what is the proper way, using Flurl, to take advantage of HTTP cache features like etag.

**Comment by tmenier** [comment]
I haven't done anything specific to support those features, but since Flurl is basically a thin facade over HttpClient with lots of hooks to manipulate that object directly if needed, the best approach is to first figure out how to do what you want with HttpClient and then translate that to Flurl. If you just need to add the relevant request headers, that's pretty easy using `WithHeader` / `WithHeaders`. Does that help?

**Comment by andresmoschini** [comment]
Yes, thanks, I did that. Anyway, please consider it for future improvements.
