### ISSUE TITLE
Ability to have PatchJsonAsync set content-type: "application/json-patch+json"

### ISSUE THREAD

**Issue by Jacob-McKay** [tmenier/Flurl#139]
Some C# libraries built to consume json PATCH requests rely on this header being set.

How do you feel about having flurl set this header automagically?

**Comment by tmenier** [comment]
Technically that header is used to indicate that you are sending a [JSON Patch document](https://tools.ietf.org/html/rfc6902), which isn't necessarily implied just because you're sending JSON and using the PATCH verb. So I wouldn't set it automatically. But I'd be open to possibly supporting JSON Patch in Flurl if it's something people want. It'd be a larger effort than just setting the header though.

**Comment by Jacob-McKay** [comment]
Do you have any contribution guidelines?

**Comment by tmenier** [comment]
Nothing formal. I like to discuss the idea in an issue first, which we've already done. Then I'm happy to consider PRs. Try to follow existing code conventions (again, not formal/documented) and be sure you have good test coverage. That's about it!

**Comment by tmenier** [comment]
At this point I don't plan on adding any first-class support for Json PATCH, but there is a related bug that's making it difficult just to set the header: #256. That one's a high priority, and once it's fixed at least it'll be easier to implement Json PATCH on your own.

**Comment by Jacob-McKay** [comment]
Sounds good, thanks for the discussion and the awesome library!
