### ISSUE TITLE
Make FlurlHttpException serializable

### ISSUE THREAD

**Issue by MNF** [tmenier/Flurl#168]
Could you please  Make FlurlHttpException serializable. 
We store last exception in Asp.Net Session and not serializable exceptions caused SerializationException during error reporting.
For more reasons see  
http://stackoverflow.com/questions/1066701/why-should-i-always-make-my-exceptions-serializable-net

**Comment by tmenier** [comment]
Good suggestion, I'll look into that.

**Comment by MNF** [comment]
Note that serialization should be conditionally compiled. It's recommended on full .net framework, but not supported on .Net Core. See
https://github.com/Microsoft/dotnet-apiport/blob/master/docs/HowTo/PlatformPortability.md

**Comment by tmenier** [comment]
Do you have a work-around for this? This upcoming release is largely about exception handling enhancements so I decided it's time to make a decision on it. I looked into it and serialization seems antiquated and very clunky to implement. I suspect these were part of the reason it wasn't brought forward to .NET Core. Also no one else has requested it. Sorry for sitting on it for so long.

**Comment by MNF** [comment]
I agree that Serializable is used by old technologies like binary serialization, but it’s very easy to implement - not more than example from https://github.com/Microsoft/dotnet-apiport/blob/master/docs/HowTo/PlatformPortability.md

```
using System;
using System.Runtime.Serialization;

namespace Application
{
#if DESKTOP
    [Serializable]
#endif
    public class SomeCustomException : Exception
    {
        public SomeCustomException() { }

#if DESKTOP
        protected SomeCustomException(SerializationInfo info, StreamingContext context)
            : base(info, context)
        { }
#endif
    }
}
```

**Comment by tmenier** [comment]
Just adding that to any exception type won't magically make it so you can serialize and deserialize it without losing information. There's a lot more to it. See here:

https://stackoverflow.com/questions/94488/what-is-the-correct-way-to-make-a-custom-net-exception-serializable

`FlurlHttpException` would be particularly complicated because it contains that `HttpCall` object, which is rich and deeply nested, containing the request and response messages, which contain streams and whatnot. It would get very messy very fast.
