### ISSUE TITLE
Calling Dispose() on child FlurlClient results in child being reusable but not the parent. New child clients can no longer be created nor can requests be made.

### ISSUE THREAD

**Issue by gjlumsden** [tmenier/Flurl#178]
I have encountered a situation when using a shared `FlurlClient` when managing its lifetime directly so that its underlying `HttpClient` and `HttpMessageHandler` can be reused across multiple threads and concurrent requests. The following code highlights the issue:

```C#
private FlurlClient parentClient = new FlurlClient();
public async Task<ResultType> MakeRequestAsync()
{
	var childClient = parentClient.WithUrl(aFlurlUrl);
	var result = await childClient.GetAsync();
	childClient.Dispose();
	
	//Call to childClient.HttpClient returns a newly created HttpClient and can be reused (HttpClient.disposed is false)
	//Call to parentClient.GetAsync() or parentClient.WithUrl(...) to get a new child then attempting to use it throws ObjectDisposedException (parentClient.HttpClient.disposed is true)
	
	return result;
}
```
The first request to `MakeRequestAsync()` will succeed, however subsequent calls will fail with an `ObjectDisposedException` until the parent client is recreated. However, it is still possible to reuse `ChildClient` within `MakeRequestAsync()` before it returns since `EnsureHttpClient(HttpClient hc = null)` is called to recreate it. This method calls the parent's `EnsureHttpClient` method to set the recreated `HttpClient` but it is never set since its `HttpClient` is not null.

It's odd that calling dispose on the child doesn't then prevent it from being reused, but prevents the parent from being reused (either for requests directly or to create new usable child clients).

I'd be happy to take on this issue if it's decided that it is a bug and needs resolved.

One option would be to prevent calling `Dispose()` on anything cloned from the parent when the `_parent` field is not null then setting the child's reference to any cloned field to null and implementing a `CheckDisposed()` method to throw an `ObjectDisposedException` on any subsequent usage of the disposed client. This would allow the parent client to be usable until it is explicitly disposed by its owner.

**Comment by thiagolunardi** [comment]
That's because when you use the `FlurlClientExtensions` as `WithUrl(url)`, this is cloning the parent client, and not copy or creating a new instance of.

So, when you are disposing the `childClient`, actually, you are disposing the `parentClient` itself.

You can check that at [`Flurl/ClientConfigExtensions.cs`](https://github.com/tmenier/Flurl/blob/master/src/Flurl.Http.Shared/ClientConfigExtensions.cs#L24-L30).

**Comment by gjlumsden** [comment]
@thiagolunardi I've checked the code, I understand what's happening and how it's happening. However, I don't think what's happening is necessarily correct nor particularly friendly.

I don't think it's right that disposing an the child client cloned from the original allows the clone to be reused after calling `Dispose()` but the original (which is created to _be_ reused so that I can reuse the `HttpClient` as is best practice) unusable. It seems to defeat the purpose, especially when best practice for anything that implements `IDisposable` is to call `Dispose()` at the earliest opportunity.

**Comment by tmenier** [comment]
First, I think you're correct that there is a bug here. A FlurlClient shares an instance of HttpClient with all of its clones, so obviously when HttpClient is disposed for one, it's disposed for all. However, by design, a FlurlClient can still be reused after Dispose is called; it'll simply instantiate a new HttpClient as needed. What signals it to do this is its internal reference to HttpClient is null, which is set on Dispose. **But if the FlurlClient is cloned from a parent, the parent's HttpClient reference is not set to null when the child is disposed, so it's "stuck" referencing a disposed instance.** That's the bug in a nutshell.

That said, I don't think what you're trying to do here is optimal. It's worth noting that the cloning behavior is more or less an implementation detail that you usually don't need to worry about. FlurlClient is basically a wrapper around a Flurl.Url and an HttpClient. The fluent syntax pretty much dictates that the Url part needs to exist first, and the cloning behavior is just a way to achieve reusing the HttpClient with multiple Urls. Clones are very cheap to create since they're sharing the "heavy" part, and if there are lots of them hanging around waiting to be garbage collected, it likely isn't going to matter.

So my advice here would be to code your solution as though you want a single shared FlurlClient and just reuse it they way you would a shared HttpClient. I don't think your code needs to be concerned with the cloning behavior at all.

```C#
private FlurlClient client = new FlurlClient();
public async Task<ResultType> MakeRequestAsync()
{
	// despite cloning, you'll never have more than 1 HttpClient instance, so this should be good enough!
	return client.WithUrl(aFlurlUrl).GetAsync();
}
```

**Comment by gjlumsden** [comment]
@tmenier Apologies for the delay responding here.

> However, by design, a FlurlClient can still be reused after Dispose is called; it'll simply instantiate a new HttpClient as needed

This makes total sense. Its heavy stuff is cleaned up, if it's reused they're recreated. I like this pattern having thought about it. My suggested fix would break this completely!

> So my advice here would be to code your solution as though you want a single shared FlurlClient...

That is what I've done. `return client.WithUrl(aFlurlUrl).GetAsync();` is essentially the pattern I'm using now.

Given the blanket advice is to dispose an `IDisposable` as soon as it's not needed, might it be worth returning a different type which implements the same contract as a `FlurlClient` but not `IDisposable` when created from a parent? I appreciate this might be over the top, but (when this bug is fixed) users might be creating child clients and disposing them, all the while thinking they are reusing the underlying `HttpClient` in the parent `FlurlClient` which won't be the case. It might be better to just document this, I guess.

Thanks for your feedback. Is it OK if I pick up the fix for this bug? It'll be a case of ensuring the `parent.HttpClient` is set to `null` when a child is disposed?

**Comment by tmenier** [comment]
Sure, feel free if you'd like to take a crack at it. And sorry for the delay. I'm definitely inclined to keep it simple by just setting `parent.HttpClient` to null (recursively) when the child is disposed.

I generally agree with you about the blanket advice on `IDisposable`, but it seems to be universally agreed that [HttpClient](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) [is](http://bartwullems.blogspot.com/2016/09/dont-dispose-your-httpclient.html) [different](https://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed). Was it an unfortunate decision that it even implements `IDisposible`? I'm not sure, but rather I decided to just follow the same pattern with FlurlClient rather than have an "opinion" on it. It seemed the most intuitive to say manage the lifespan of a FlurlClient the way you would an HttpClient, and that disposing the former disposes the latter. So it might be worth repeating that while I agree that this is bug, it's not one you'll likely encounter if you're using Flurl the way it was designed to be used.

**Comment by tmenier** [comment]
Looking at this again, recursively setting `parent.HttpClient` to null won't solve this. What if it's the parent that's disposed? You'd have the same problem with the child. Or if you have 2 children cloned from the same parent and dispose one of them, you'd have the same problem with the sibling.

Hmm...a proper fix would be more elaborate than I'd like. In hindsight it probably would have been better _not_ to allow reusing FlurlClient after it's disposed and just let it throw `ObjectDisposedException`. At least it's consistent vs. parent behaving one way and clones another way. I'm ok with just calling this a known issue and saying "don't do that". With my plans for Flurl.Http 2.0, the cloning behavior hopefully won't even be necessary.

**Comment by gjlumsden** [comment]
I have been mulling this over myself and have effectively drawn the same conclusion as you. It works great, as long as you are aware of the traps. Looking forward to 2.0!
