### ISSUE TITLE
Ability to handle REST style URL's with slash delimited key-value pairs

### ISSUE THREAD

**Issue by dljones555** [tmenier/Flurl#216]
Appreciate Flurl. I don't see the ability to handle REST URL's like this:

http://www.example.com/customers/33245/orders/8769/lineitems/1

URL Builder seems oriented to key value pairs like ?key=value in querystring.

Am I missing something in the functionality? I wrote a quick extension method to achieve what I wanted and use the WebAPI style parameter syntax.

Is there another approach that should be considered?

```
var url = new Url("http://www.example.com");

url.SetPathParameters(new { customerId = 33245, orderId = 8679, lineItemId = 1}, "customers/{customerId}/orders/{orderId}/lineitems/{lineItemId}";

public static Url SetPathParameters(this Url url, object obj, string segment)
{
     var kvp = ObjectToKV(obj);
     foreach (var kv in kvp)
     {
          segment = segment.Replace("{" + kv.Key + "}", kv.Value.ToString());
     }
     return url.AppendPathSegment(segment);
}
```

**Comment by tmenier** [comment]
Yes, you're missing `AppendPathSegments`.

```c#
"http://www.example.com"
    .AppendPathSegments("customers", custId, "orders", ordId, "lineitems", itemId)
```

**Comment by dljones555** [comment]
Ok, thanks. I see how that could work.

I still would prefer an approach like I suggested that would do a replacement of values on a single segments string. On my API, I have a generic command interface, which builds the URL. 

` public virtual async Task<T> ExecuteCommand<T, R>(R object, string segments, int retryCount = 1, int delaySeconds = 5)`

**Comment by tmenier** [comment]
That approach is similar to [UriTemplate](https://msdn.microsoft.com/en-us/library/system.uritemplate.aspx). It's a perfectly valid way to solve the problem, Flurl just takes a different approach that in my view is equally effective. I would not at all say Flurl is more "oriented" toward query strings. If you prefer the token replacement approach, go for it. As you've shown it plays nicely with Flurl. But as a core library feature I'd prefer not to have 2 different ways to solve the same problem.

**Comment by dljones555** [comment]
Respect that it's your call, but I still think it would be useful to have something that does the ObjectToKV magic with the token replacement in the Uri template. You lose that ability with the AppendPathSegments as it is, right? You have add each segment fluently.

If you're going closer to true REST, the segments would be plural and there could be a different variable name, such as "customers/{customerId}". 

I wonder what others think. :)

**Comment by tmenier** [comment]
I think we'll have to agree to disagree, but for argument sake, consider these examples:

```c#
url.SetPathParameters(new { customerId = customerId, orderId = orderId, lineItemId = lineItemId }, "customers/{customerId}/orders/{orderId}/lineitems/{lineItemId}"
url.AppendPathSegments("customers", customerId, "orders", orderId, "lineitems", lineItemId)
$"{url}/customers/{customerId}/orders/{orderId}/lineitems/{lineItemId}"
```

In terms of terseness and readability, sorry, but your way comes in last for me. You're suggesting that because Flurl supports object notation for query strings and not path segments, that somehow it gives preference to query strings and is therefore anti-REST. The reality is that path segments are supported in a way that better fits their structure. In most cases, a query string can be thought of as an **unordered collection of name-value pairs**. That fits the object paradigm very well. Paths, on the other hand, can be thought of as an **ordered list of segments**, which is better modeled by, well, a list. The fact that your `SetPathParameters` method requires that string template arg is a clue here - the object itself is not enough to fully describe the URL, so you must pass more information, and you end up with a very verbose method call compared to Flurl. (Frankly, in your case I think I might just go with string interpolation.)

The bottom line is you're not "losing" any ability to build RESTful URLs with Flurl. It supports them very directly and succinctly, just using a different paradigm than you prefer.

At this point you might be thinking, ok, but that still doesn't work with my generic command interface. My suggestion there is to drop the `segments` arg from the method signature and move that knowledge inside the method implementations. Requiring the user to pass that in seems like a leaky abstraction. Isn't the point of the command object to encapsulate the details of an API call? If the method already "knows" what the URL needs to look like, I think you'd have an a-ha moment and realize that `AppendPathSegments` or string interpolation would work really well here. The object paradigm _does_ work well for passing required data to a command or query, just not for the URL-building part _directly_, in my opinion.
