### ISSUE TITLE
For Json parsing allow 'Root Element' 

### ISSUE THREAD

**Issue by edgiardina** [tmenier/Flurl#218]
One feature that is pretty handy from RestSharp is the ability to specify  'RootElement' for Json parsing. 
Solves the problem found here:
https://stackoverflow.com/questions/13702657/deserializing-json-how-to-ignore-the-root-element

possible implementations could be an optional parameter to `.GetJsonAsync<T>(string rootElement)`

Basically to avoid creating a simple scaffolding POCO that has one property in JSON below, adding a root element saves us one unnecessary object.

```
{
   "tournament":{
      "tournament_id":"6",
      "tournament_name":"MD Pinball Championship",
      "city":"Baltimore",
      "state":"MD",
      "country_name":"United States",
   }
}
```

**Comment by tmenier** [comment]
Thanks for the suggestion. I like this idea a lot. A couple possible enhancements:

- When T is some sort of collection it could find _all_ properties of that name (such as in objects in an array).
- Support JSONPath expressions.

Like so many things in Flurl, it's a lot easier since [somebody else already did the hard part](https://www.newtonsoft.com/json/help/html/SelectToken.htm). :). I see one potential problem though: Flurl allows you to swap out `NewtonsoftJsonSerializer` for a different implementation, so those who don't want to use Json.NET for whatever reason don't have to. I don't think node traversal belongs in `ISerializer` so I'd have to either come up with something different or just say sorry, you're stuck with it if you want this functionality. (I doubt very many people would care, and you can't opt out of the Newtonsoft dependency anyway.)

**Comment by tmenier** [comment]
Closing this issue because #410 should cover it and the description is a lot closer to how I want to implement this. Feel free to comment in that issue if you have further thoughts.
