### ISSUE TITLE
Use of refresh tokens

### ISSUE THREAD

**Issue by IsmailHassani** [tmenier/Flurl#219]
Hi Todd,
First, thank you for this awesome library.

I'm struggling with an issue how to use the refresh tokens correctly. I have an WPF application that gets an acces and refresh token. I store them both in a kind of session during the application live time. When the access token is expired I get an error ("unauthorized") which triggers a global error handler.
What I actually want is that when a request is done, and the error occurs, the application retrieves a new access_token with the refresh_token and tries to resend the original request.

Is this possible? What's your advice?
With kind regards,
Ismail

**Comment by tmenier** [comment]
My recommendation is to anticipate when the access_token will expire and get a new one before it does, rather than waiting for a 401 error to happen. (Related: #213) If you don't know how long the token is good for, see if an `expires_in` field (or similar) is sent with the initial token response.

**Comment by IsmailHassani** [comment]
Hi @tmenier Thank you, I just did that. Thanx

**Comment by mxstudios** [comment]
@tmenier ,

Quick question. I have same issue and had no problem anticipating and refreshing token, The issue is when the token was revoked on the server. Expiration date is still good but get an unauthorized when the call is made. I then trap the error and get new token, but it's already after the fact. Need a way to re-call the one that failed with the new token...

Thoughts?

**Comment by tmenier** [comment]
@mxstudios I think that question is a better fit for Stack Overflow where others can benefit as well.

**Comment by tasoss** [comment]
Hello.
I suppose a solution like onAuthenticationRequired which is provided by servicestack is not included in flurl?
