### ISSUE TITLE
Custom URLEncoding

### ISSUE THREAD

**Issue by speige** [tmenier/Flurl#227]
When calling "http://myurl".GetStringAsync(); it would be nice to be able to custom url encoding. One possible way would be to encode it beforehand & have a parameter which specifies that it's already been encoded.

Flurl handles URLEncoding correctly, so this is not a bug. However, some web servers don't handle URLDecoding correctly. This is a workaround to allow working with servers which don't follow proper rules.

As an example, with the following urls, one downloads correctly and the other does not. However, the one that doesn't work is the one that's has the # (#23) symbol in the query string URLEncoded. The & (%26) symbol must be encoded or it won't work. So, this server expects a URL to be half-encoded & half-not_encoded.

https://en.wikipedia.org/wiki/Coffee_%26_More?action=info#mw-pageinfo-watchers
https://en.wikipedia.org/wiki/Coffee_%26_More?action=info%23mw-pageinfo-watchers

**Comment by tmenier** [comment]
That's not a problem with the URL, the web server, or Flurl. The # there denotes the [fragment](https://en.wikipedia.org/wiki/Fragment_identifier); it's not part of the path and so it's not supposed to be encoded.  Flurl recognizes this and won't encode it.

What exactly is the problem here? Can you demonstrate it?

**Comment by speige** [comment]
You're right. It was a bug in my code that was causing the error. Flurl & the web server are fine. We can close this. Sorry to waste your time.

Excellent library by the way. Thanks!
