### ISSUE TITLE
Come up with a better way to work with failed response bodies

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#23]
http://stackoverflow.com/questions/27686254/flurl-http-custom-error

**Comment by lmcnearney** [comment]
:+1: 

I would have to agree that handling errors is currently a pain. Perhaps there should be an option to suppress throwing an exception if a non-200 HTTP response is returned? That way the developer can decide how to handle it manually like when using the built-in HttpClient or RestSharp client.

**Comment by tmenier** [comment]
I would definitely consider something like that. Currently you can get at the "raw" `HttpResponseMessage` via `GetAsync()`, but you're right that you can't suppress the exception on non-200s. Maybe a good first step is just a bool param on `GetAsync`, `PostAsync`, etc. that does just that. Ultimately I'm aiming for a slick way to get an error poco out of a JSON API but haven't worked out the details just yet.

Thanks for the suggestion. If you have anymore thoughts on what any of this should look like, I'm all ears.

**Comment by rshillington** [comment]
If you're taking votes, add my name to the list for a way to opt-out of the Exception on non-sucess responses.

**Comment by lmcnearney** [comment]
@tmenier Thanks for looking into the issue. Is there any way to disable the exception handling on a per-request basis instead of setting it as part of the global configuration? I would still want to use the convenience methods for some requests but disable the error handling when dealing with APIs that return non-200 codes in the normal flow.

**Comment by tmenier** [comment]
Just to be clear, do you care what the status code is in these cases (i.e. are you making decisions based on it), or do you just want a way to tell the convenience methods to proceed with deserializing regardless of the status code?

**Comment by lmcnearney** [comment]
I care about the status code for certain requests but I would use the non-convenience methods to manually inspect the response in those cases and would like to disable the exception handling for just those requests. A good example would be making a GET or HEAD request to see if an element already exists as part of some logic. As it is now, you have to wrap everything in a try/catch block instead of simply checking the status code of the response.

For convenience methods, throwing an exception makes sense as there's more magic happening and I wouldn't expect the serializer to work properly in the case that it received an invalid response.

Does that make sense?

**Comment by tmenier** [comment]
Completely, and I'll give it some thought. In the mean time, you might want to create a few of your own extension methods to encapsulate the try/catch logic. Or, you may still be able to leverage the global error handler - there's a lot of diagnostic info in that `call` object and if you can figure out a way to identify calls where you want to suppress exceptions, you can set `ExceptionHandled` accordingly. Not as good as preventing the exceptions from being thrown in the first place, but might ease the pain for now.

**Comment by tmenier** [comment]
New error response helpers released in 0.5.0. Details:
http://stackoverflow.com/questions/27686254/flurl-http-custom-error/28332184

**Comment by tmenier** [comment]
I'm considering this particular issue resolved. @lmcnearney @rshillington I think configuring which status codes don't throw is a different issue, so I moved it [here](https://github.com/tmenier/Flurl/issues/28).
