### ISSUE TITLE
FlurlRequest.Settings must be merged in FlurlRequest ctor 

### ISSUE THREAD

**Issue by ssh-git** [tmenier/Flurl#239]
Hello. settings for client does not applied for FlurlRequest in next case:

Config with 
```
FlurlHttp.ConfigureClient("restEndpoint", config =>
{
    var jsonSettings = new JsonSerializerSettings
    {
        NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore
    };
    config.JsonSerializer = new NewtonsoftJsonSerializer(jsonSettings);
});
``` 
execute next code
```
var request = restEndpoint.AppendPathSegment("some segment").WithHeader("some header","some value");  
var jsonString = request.Settings.JsonSerializer.Serialize(new {MustNotIncludeInJson = default(string), Data = "some data"});
```
jsonString will be  **{"MustNotIncludeInJson":null,"Data":"some data"}** but must be **{"Data":"some data"}**

If before jsonString trigger get for FlurlRequest.Client all will be correct.

This happens because get on Client trigger Settings.Merge. This must be done in FlurlRequest constructor

From FlurlRequest source 
```
public class FlurlRequest : IFlurlRequest
{
	private IFlurlClient _client;
	
	public FlurlRequest(Url url = null) {
		Settings = new FlurlHttpSettings();
		Url = url;
	}
	
	public FlurlHttpSettings Settings { get; set; }
	
	public IFlurlClient Client {
		get {
			if (_client == null) {
				_client = FlurlHttp.GlobalSettings.FlurlClientFactory.Get(Url);
				Settings.Merge(_client.Settings);
			}
			return _client;
		}
		set {
			_client = value;
			Settings.Merge(_client?.Settings ?? FlurlHttp.GlobalSettings);
		}
	}
```

**Comment by tmenier** [comment]
Thanks for reporting. I was able to prove it with this failing test:

```c#
[Test]
public void request_gets_client_settings_when_client_exists() {
    FlurlHttp.ConfigureClient("http://test.com", settings => settings.CookiesEnabled = true);
    var req = new FlurlRequest("http://test.com");
    Assert.IsTrue(req.Settings.CookiesEnabled);
}
```

Basically the problem is that when you don't set `FlurlRequest.Client` explicitly, getting the client is deferred until just before the request is sent. This is by design because `FlurlRequest.Url` is used to determine whether to use a cached client, and that value can change at any time. But, reading inherited settings is a case where you need it sooner.

It's a little tricky to solve but I'll get it fixed for the next maintenance release. In the mean time I imagine it's easy enough to work around it? I do think it's probably limited to cases where you use `FlurlHttp.ConfigureClient` _and_ you need to read the request-level settings before the call is made, which is probably a little rare but certainly legitimate.

**Comment by tmenier** [comment]
This is fixed, please test the prerelease: https://www.nuget.org/packages/Flurl.Http/2.1.0-pre

**Comment by tmenier** [comment]
released
