### ISSUE TITLE
FlurlRequest.Settings.JsonSerializer is ignored when using HttpTest

### ISSUE THREAD

**Issue by hmvs** [tmenier/Flurl#246]
Seems to be Settings.JsonSerializer is ignored when using HttpTest
```
[Test]
public async Task serializer_for_request_should_be_used_in_testmode() {
	using (var httpTest = new HttpTest()) {
		var mockSerializer = new MockSerializer();
		var flurlRequest = new FlurlRequest("http://test.com/") {
			Settings = { JsonSerializer = mockSerializer }
		};
		//Assert.AreEqual(mockSerializer, flurlRequest.Settings.JsonSerializer);

		httpTest.RespondWith(@"{""Test"":""test""}");

		var testObj = await flurlRequest
			.PostJsonAsync(new {Test = "test"})
			.ReceiveJson<TestObj>();
		
		Assert.IsTrue(mockSerializer.DeserializeStreamUsed || mockSerializer.DeserializeUsed);

		httpTest.ShouldHaveCalled("http://test.com/");
	}
}

private class MockSerializer : ISerializer {
	public bool DeserializeUsed { get; set; }
	public bool DeserializeStreamUsed { get; set; }
	public string Serialize(object obj) {
		return @"{""Test"":""yoooooooooooooo""}";
	}
	public T Deserialize<T>(string s) {
		DeserializeUsed = true;
		return default(T);
	}
	public T Deserialize<T>(Stream stream) {
		DeserializeStreamUsed = true;
		return default(T);
	}
}

private class TestObj {
	public string Test { get; set; }
}
```

None of `Deserialize` methods was used.

**Comment by tmenier** [comment]
Settings at the `HttpTest` level take precedence over everything, because it's far more likely that the subject under test would be messing with request-level settings and not the test itself, and the whole purpose of test-level settings is to override any settings inside the test subject, regardless of level. This should do what you want:

```c#
using (var httpTest = new HttpTest()) {
    httpTest.Settings.JsonSerializer = new MockSerializer();
    ...
}
```

Having said that, this still might be a bug. Since you didn't _explicitly_ set a value at the test level, I think the request-level setting should have taken precedence over the global default. I will look into it, but in the mean time consider the above a work-around.

**Comment by hmvs** [comment]
Yeah, already used this workaround. Found it when I wanted to fix this issue. But haven't found any easy way how I can do it. As far as `TestFlurlHttpSettings` invokes `ResetDefaults` and actually adds `ISerializer` to dictionary, need some default value indicator.

**Comment by tmenier** [comment]
This is fixed, please test the prerelease: https://www.nuget.org/packages/Flurl.Http/2.1.0-pre

**Comment by hmvs** [comment]
Work like a charm. Thank you.

**Comment by tmenier** [comment]
released

**Comment by hmvs** [comment]
Updated. Removed workaround. Works fine. Thank you
