### ISSUE TITLE
HttpTest does not call error callbacks

### ISSUE THREAD

**Issue by hendrik-rebuy** [tmenier/Flurl#25]
Great Library, I'm very happy with it so far. Only hiccup was when testing error callbacks with the builtin httpTest framework the error callbacks didn't work, the exceptions were never caught. Since the before callback does work this is confusing to me. 
Had to use an external Mock Server to test the error callbacks, seems a little bit unnecessary.

**Comment by hendrik-rebuy** [comment]
After playing around some more and looking into the code, I see that I was confused because the error callbacks only catch exceptions on the sendAsync (e.g. no connection) and not the FlurlExceptions for bad request for example also json serialization exceptions aren't caught. 

So it wasn't an issue with the testing framework.

But still I have to ask whats the reasoning for only catching the low level exceptions? I would expect to have a callback on every single exception that comes from a call to the library with an onError callback.

**Comment by tmenier** [comment]
Hi Hendrik,
Thanks for pointing this out. I do see your point - not all error conditions will cause `OnError` to be fired, and that behavior was not intentional. I'll consider this a high-priority issue and address it soon.

**Comment by hendrik-rebuy** [comment]
Thanks sounds good.

**Comment by tmenier** [comment]
This issue should be fixed in the latest version on NuGet (0.4.1). However, now that I re-read your comments I realize that serialization exceptions are an example of something that is still not intercepted by OnError. I'll need to think on that some more as it's a bit more involved. For now just know that all HTTP-related exceptions, including non-200 responses, are now intercepted correctly and the higher-level FlurlHttpException is passed to the handler.

Thanks again for reporting this.

**Comment by hendrik-rebuy** [comment]
Thanks for the fast reply the patch already helped us a lot.
