### ISSUE TITLE
Support for comparison operator 

### ISSUE THREAD

**Issue by paritoshmmmec** [tmenier/Flurl#250]
SetQueryParam will yield in equalto.  how I can support greater than operator

**Comment by tmenier** [comment]
I don't understand the question. Please provide an example of a URL you want to end up with.

**Comment by paritoshmmmec** [comment]
Here is sample url

anyurl?page=2&perPage=200&dateentered>=1/1/2017

the way I am creating this url 

             ```
    var url=     Url .SetQueryParam("dateentered>", "1/1/2017")
                .SetQueryParam("createAt<", "1/1/2017")
```


It might considered as hack :)

**Comment by paritoshmmmec** [comment]
Thanks for wonderful library though @tmenier

**Comment by tmenier** [comment]
Although not strictly a standard, `=` and `&` are almost universally supported by web frameworks to allow parameter passing in query strings, which is why Flurl supports that notation directly. Comparison operators may be supported by some specific web app or API, but it's not a common convention. I think the way you're doing it is fine.
