### ISSUE TITLE
encoding path segment

### ISSUE THREAD

**Issue by reazhaq** [tmenier/Flurl#253]
## Url path slash ('/') encoding issue
Assume the URL is in the form of http://www.foo.com/{product}/{department}/{category}?abc=xyz... where department is "men" and category is "indoor/outdoor".  Expected URL is "http://www.foo.com/men/indoor%2Foutdoor?abc=xyz"...

### Simple way - based on doc path segments are not encoded only query portion
```
var url1 = "http://www.foo.com".AppendPathSegments("men", "indoor/outdoor").SetQueryParam("abc", "xyz");
Debug.WriteLine(url1); // http://www.foo.com/men/indoor/outdoor?abc=xyz
```

### Pass encoded string - it magically gets decoded
```
var url2 = "http://www.foo.com".AppendPathSegments(WebUtility.UrlEncode("men"), WebUtility.UrlEncode("indoor/outdoor")).SetQueryParam("abc", "xyz");
Debug.WriteLine(url2); // same result...
```

### No luck using Url.Combine
```
var url3 = Url.Combine("http://www.foo.com", "men", "indoor/outdoor").SetQueryParam("abc", "xyz");
Debug.WriteLine(url3);

var url4 = Url.Combine("http://www.foo.com", WebUtility.UrlEncode("men"), WebUtility.UrlEncode("indoor/outdoor")).SetQueryParam("abc", "xyz");
Debug.WriteLine(url4);
```

Please advise
Thanks
-- btw, excellent library

**Comment by tmenier** [comment]
The "simple way" example is correct by-design behavior.

The second and third examples are indeed bugs, and I have verified. The intent is to encode _illegal_ characters only (not _reserved_ characters like `/`) and avoid double-encoding sequences that are already percent-encoded. The implementation attempts to do this using `Uri.EscapeUriString` and working around a [quirk](https://stackoverflow.com/a/47636037/62600) that could cause double encoding. The work-around isn't quite right - it works for illegal characters (like spaces) are already encoded, but encoded reserved characters are getting double encoded. Back to the drawing board.

Generally it's best to design URL paths that don't require escaping. I know RESTful URLs often have variable values in them, but it's a best practice use slugs or otherwise restrict what characters are allowed. Probably helps explain why this hasn't been uncovered sooner. Nonetheless, it is a bug and I'll get it on the roadmap. Thanks for reporting.

**Comment by reazhaq** [comment]
Thanks....

**Comment by tmenier** [comment]
Because it's the holidays and I'm in a giving mood, I'm giving you both a bug fix and a new feature :)

**Bug fix**
This will leave your %-encoding alone: `url.AppendPathSegment(WebUtility.UrlEncode("indoor/outdoor"))`

**Feature**
This will actually do the %-encoding for you: `url.AppendPathSegment("indoor/outdoor", true)`

So setting the new (optional) `fullyEncode` argument to `true` is appropriate when you know you want exactly 1 path segment but it's arbitrary data that could need encoding. If you're more or less hard-coding something like `"path/to/endpoint"` where you don't want those `/` characters encoded, don't use the new arg.

It should be noted that I have no plans to add the `fullyEncoded` arg to related methods like `AppendPathSegments` (plural) or `Url.Combine`.  Those take an arbitrary number of args of any type (`params object[]`), so adding a `bool` at the end doesn't work. When you need full encoding, you just need to use `AppendPathSegment`.

**Comment by tmenier** [comment]
Fixed and released.

**Comment by reazhaq** [comment]
thx....
I shall give it a try on Monday...

**Comment by reazhaq** [comment]
it is working....

**Comment by RyanPearson** [comment]
@tmenier I have tried the 2 methods which you have suggested above, and I still find that slashes (/) are magically decoded when the request is sent.

These comments suggest that it once worked, so I am wondering if it is just something which I am doing wrong.

More detail can be found in our StackOverflow post; https://stackoverflow.com/questions/52739577/dealing-with-double-encoding-in-flurl-http-get-requests
