### ISSUE TITLE
Remove TestFlurlClientFactory

### ISSUE THREAD

**Issue by aivascu** [tmenier/Flurl#269]
When testing a service that uses the ```IFlurlClientFactory``` as a dependency, using the test class ```TestFlurlClientFactory```, yields an exception saying:

```
Cannot create a Request. BaseUrl is not defined and no segments were passed.
```

**Comment by aivascu** [comment]
I provided a fix for this issue in https://github.com/tmenier/Flurl/pull/270

**Comment by tmenier** [comment]
Not sure if you tried running the test suite but I can't accept the PR because it causes `TestingTests.can_fake_cookies` to fail.

What I discovered in your case is that you don't need to use `TestFlurlClientFactory` here. It doesn't play a role in faking/recording calls at all. Just pass an instance of `PerBaseUrlFlurlClientFactory` - the call will still be faked and your test will pass.

This made me question my design decision though. Does `TestFlurlClientFactory` even need to exist? I'm thinking no. It basically just returns the same `FlurlClient` instance for every call. But if the tests just use whatever the global setting is by default, all of my tests pass. I can understand why you might assume you should use it in your test, but if it doesn't exist you won't be tempted. :)

**Comment by aivascu** [comment]
@tmenier well I guess I used it because the name of the class implied it is a fake implementation of ```IFlurlClientFactory``` intended to be used as a mock. 🤷‍♂️ 
I agree removing it might be a good decision.

**Comment by tmenier** [comment]
I agree, the name is misleading. It'll be gone in 2.2.

**Comment by tmenier** [comment]
Released.
