### ISSUE TITLE
Base adress is not set if using flurlClientFactory.Get(Base_ADR) 

### ISSUE THREAD

**Issue by stjephan** [tmenier/Flurl#284]
I like to use the IFlurlClientFactory in my asp.net core 2.0 application. 

I get the following exception **System.ArgumentException: 'Cannot create a Request. BaseUrl is not defined and no segments were passed.' 

Code:
```
public class MyWebService {
 private string BaseUrl {
  get;
 }
 private IFlurlClient FlurlClient {
  get;
 }

 public MyWebService(IFlurlClientFactory flurlClientFactory) {
  FlurlClient = flurlClientFactory.Get(BASE_ADR); < --Setting BASE_ADR There has no effect.
  BaseUrl = "myBaseUrl";
 }

 public async Task < SearchResult > CallService(SearchParamsDto searchParams) {
  FlurlClient.BaseUrl = BaseUrl; < --If set it here again it works
  SearchResult result = await RetryPolicy.ExecuteAsync(() =>
   FlurlClient.Request()
   .AppendPathSegments("test", "me") // Personensuche
   .SetQueryParam("callingService", "itsme")
   .PostJsonAsync(searchParams).ReceiveJson < SearchResult > ());
  return null;
 }
}
```

I tried to do use it in a small console application:

```
PerHostFlurlClientFactory clientfactory = new PerHostFlurlClientFactory();
MyWebService service =  new MyWebService (clientfactory);
```

**

**Comment by tmenier** [comment]
Use `PerBaseUrlFlurlClientFactory` instead of `PerHostFlurlClientFactory` and `BaseUrl` will be set for you. When you want a `FlurlClient` singleton for all instances of a _specific service_, which it appears you do, that is the factory implementation you want to use. See [here](http://tmenier.github.io/Flurl/client-lifetime/) for details.
