### ISSUE TITLE
system.typeloadexception

### ISSUE THREAD

**Issue by muhammetsahin** [tmenier/Flurl#31]
Hi,

Im using Xamarin PCL 

and tried this code:

public async Task<AccountDto> GetAccountAsync (string username, string password)
		{
			AccountDto result = null;
			using (var fc = new FlurlClient ().EnableCookies ()) {
			
					try {
						result =	await ApiConsumer.Url
							.AppendPathSegment ("account/token")
							.WithClient (fc)
							.PostJsonAsync (new { UserName = username, Password = password})
							.ReceiveJson<AccountDto> ();

						
					} catch (FlurlHttpTimeoutException) {
						Debug.WriteLine ("Timed out!");
					} catch (FlurlHttpException ex) {
						if (ex.Call.Response != null)
							Debug.WriteLine ("Failed with response code ");
						else
							Debug.WriteLine ("Totally failed before getting a response! " + ex.Message);
					}

					return result;
			
			}

But i've got exception.

**Comment by tmenier** [comment]
Happy to help, but 2 requests:

 1. Please [post the question on Stack Overflow](http://stackoverflow.com/questions/ask?tags=flurl+http+.net+c%23) so it's easier for others to find and benefit from.

 2. Please provide as much detailed information about the exception as possible.

**Comment by muhammetsahin** [comment]
OK.

Im using PCL Profile 78

Flurl version 1.0.7
Flurl.Http version 0.5.3

Thnks:)

Interesting thing is i tried same code on VS2012 console project it was work.

![image](https://cloud.githubusercontent.com/assets/2045788/6825159/0a0cbe84-d301-11e4-904c-c537efe89ff3.png)

**Comment by tmenier** [comment]
While I still would have preferred you'd moved your question to Stack Overflow, I'll answer here.

I suspect the issue is related to Json.NET. Although Flurl.Http has a depnendency on it, try installing the Json.NET NuGet package into your Xamarin project. (I actually started getting the same exception in my PCL unit tests at one point, and referencing Json.NET directly from the test project fixed it.)

If that doesn't work, I'd suggest looking through [this thread](http://forums.xamarin.com/discussion/9011/system-typeloadexception). I cannot reproduce myself, but a quick [Google search](https://www.google.com/?q=system.typeloadexception+json.net#q=system.typeloadexception+json.net+pcl) shows lots of others have seen similar issues and might provide some good leads.

**Comment by muhammetsahin** [comment]
Thank you i solved:)
