### ISSUE TITLE
HttpTest with TLS 1.0 disabled

### ISSUE THREAD

**Issue by jonbock** [tmenier/Flurl#316]
We have recently disabled TLS 1.0 on our servers and caused test implementations with HttpTest to fail, found a solution so would like to submit a pull request to resolve this as we use flurl in a number of projects.

**Comment by jonbock** [comment]
Would like to create a pull request for this feature issue.

**Comment by jonbock** [comment]
Should be a simple fix, will check in my fork for you to have a look, not sure if its the best place to put it

**Comment by tmenier** [comment]
@jonbock I don't think I'm going to accept this for the following reasons, but let me know if I'm way off base here:

1. You're just calling a static method on `ServicePointManager`. You can just do that in your own code and it will have the same effect. Why add it to the library?

2. The whole point of `HttpTest` is that it allows you to mock calls rather than actually making them, so when an `HttpTest` instance is "alive", Flurl-based HTTP calls shouldn't be hitting your server at all. So anything you changed on your server wouldn't affect these calls.

Maybe I need more details about how your tests are failing in order to understand the issue?

**Comment by tmenier** [comment]
Haven't heard back from you so closing this. Let me know if you don't think my reasoning above is valid.
