### ISSUE TITLE
Potential issue with PerHostFlurlClientFactory implementation

### ISSUE THREAD

**Issue by willapp** [tmenier/Flurl#322]
We've recently started using Flurl in our existing large commercial suite of web applications, and it's a fantastic library (thanks!). However, we uncovered an issue with the way we get re-use from `HttpClient`, and while it may be by design, I'm not sure if other users are likely to fall foul of the same situation.

Essentially we have two endpoints that share the same host, but one is secure and the other isn't:

```
http://myservice.com/blah
https://myservice.com/etc
```

We decided against using the provided `PerBaseUrlFlurlClientFactory` because some of our endpoints contain unique path values that would cause us to create lots of `FlurlClient` instances unnecessarily. Instead, we used the `PerHostFlurlClientFactory` to get better re-use. The problem comes with the above scenario, because we use a custom `HttpClientFactory` that adds some automatic certificate validation to secure endpoints.  If the client is created first against the non-secure endpoint, the certificate validation logic is not added, and when a request goes to the secure endpoint, the same client is re-used and the call fails.

By definition, I understand that the `PerHostFlurlClientFactory` is designed to only key clients by Host, but this seems insufficient when `Scheme` and `Port` can vary and have a big impact on whether calls will succeed or fail, particularly in the above SSL scenario where certificate validation should occur.

We have worked around this by creating a new client factory implementation that keys the clients on scheme, host, and port, but I thought I would raise this for discussion as to whether this should really be the default behavior of the `PerHostFlurlClient` factory? Is there a downside to offset the benefit of avoiding the issue that we encountered?

**Comment by tmenier** [comment]
An API where some endpoints are encrypted and others aren't is more unusual than you might think. SSL everywhere seems to be the standard. So I'm not too concerned about this biting too many people. That said, I'm inclined to agree that taking scheme & port into consideration by default is probably better. The downside of such a change is that it's potentially breaking. If someone does have the same scenario as you, and they configure a shared per-host client to, say, pass a default header on every call, this change would cause that header to be omitted on calls made on the "other" client.

**Comment by tmenier** [comment]
@willapp Yep, I would consider this change in 3.0, but unfortunately that doesn't have so much as a roadmap started and could be a very long ways out. But, consider this a start. :)

**Comment by tmenier** [comment]
@rcollette Are you confusing Flurl's `HttpClientFactory` with ASP.NET Core's? They're 2 very different things. Or am I not understanding what you're getting at?

**Comment by rcollette** [comment]
I might be.   I thought the intent of both was to reduce socket allocation (and probably other issues).  My understanding was that it was implemented in Flurl as per best practice recommendations from MS.   Then they added HttpClientFactory to kind of enshrine that in the framework itself.   Maybe I need to go back to the Flurl docs, it has been a while since I have looked at them.On Jan 29, 2019 5:00 PM, Todd Menier <notifications@github.com> wrote:@rcollette Are you confusing Flurl's HttpClientFactory with ASP.NET Core's? They're 2 very different things. Or am I not understanding what you're getting at?

**Comment by tmenier** [comment]
@rcollette No worries, there's definitely been some confusion in this area, largely because naming coincidence. (For the record, my `HttpClientFactory` came first...lol.) Just know that if you're targeting .NET Core 2.1 or above, you're getting MS's new socket management stuff automatically. This should help clear it up:

https://stackoverflow.com/questions/51037357/flurl-client-lifetime-in-asp-net-core-2-1-and-ihttpclientfactory

**Comment by tmenier** [comment]
I promised I'd consider this for a future major release, just didn't imagine that would be 2+ years out. :) Here are my thoughts:

1. I'm not going to change `PerHostFlurlClientFactory` because [by definition of "host"](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Examples) I think it behaves as expected.

2. But should a new factory be introduced that takes scheme and port into account, and should that be the new default? I'm thinking yes. The main reason to reuse `HttpClient`/`HttpMessageHandler` is to avoid [socket exhaustion](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/), but I don't _think_ a socket could be reused with different ports/schemes anyway. (I'd love it if someone could confirm that, I'm not an expert in the low-level stuff.)

So given your use case (and possibly others), the combination of scheme, host, and port may be the most optimal context for creating/reusing clients by default.

**Comment by tmenier** [comment]
Closing in favor of #550, which is ready to go. (I thought it made sense to summarize the change in a new issue.)

**Comment by tmenier** [comment]
#550 is released: https://www.nuget.org/packages/Flurl.Http/3.0.0-pre5
