### ISSUE TITLE
Error building Xamarin Forms Android project with Flurl 1.2.0 reference

### ISSUE THREAD

**Issue by xzuttz** [tmenier/Flurl#333]
Hi there!

In my Xamarin Forms (Android) project, I am referencing a library that uses Flurl 1.2.0.

Do you know if this will be solved, if I upgrade Flurl to 2.x ? 

VSTS Build with the Xamarin Forms Android template gives the below error:

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1812):C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1812,5): Error MSB4018: The "LinkAssemblies" task failed unexpectedly. Mono.Linker.MarkException: Error processing method: 'System.String Flurl.Http.Configuration.DefaultUrlEncodedSerializer::Serialize(System.Object)' in assembly: 'Flurl.Http.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.String Flurl.Url::EncodeQueryParamValue(System.Object,System.Boolean) at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference) at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference) at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction) at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body) at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method) at Mono.Linker.Steps.MarkStep.ProcessQueue() --- End of inner exception stack trace --- at Mono.Linker.Steps.MarkStep.ProcessQueue() at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue() at Mono.Linker.Steps.MarkStep.Process() at Mono.Linker.Steps.MarkStep.Process(LinkContext context) at Mono.Linker.Pipeline.Process(LinkContext context) at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context) at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res) at Xamarin.Android.Tasks.LinkAssemblies.Execute() at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
> --
> Process 'msbuild.exe' exited with code '1'.

**Comment by kvpt** [comment]
By the error it's this commit who change public api :
https://github.com/tmenier/Flurl/commit/f1a9718061f233942e77b467604b1b5c357127e8

It's for Flurl 2.7.1 and Flurl.Http 2.1.1 so if you have this error it's probably because you have packages versions mismatch inside your solution.

If you have several projects in your solution check the nuget windows to verify if you need to consolidate the packages versions.

Also, in the new project system the packages references are now transitive.
So you have to reference Flurl and Flurl.Http to have compatible version, otherwise nuget takes the minimum version dependency which can be incompatible (when public api are modified like here).

Sometimes the solution is simply to clean obj and bin folder to clear old dlls versions.

**Comment by tmenier** [comment]
@xzuttz Try what was suggested above (update/consolidate versions, clean your obj/bin folders). If you're still having issues, I suggest posting a question to Stack Overflow. I honestly don't know the answer, sorry.
