### ISSUE TITLE
Implement equality for Url instances

### ISSUE THREAD

**Issue by hravnx** [tmenier/Flurl#337]
Flurl vs 2.7.1 

The C# expression `(new Url("http://example.org")) == (new Url("http://example.org"))` evaluates to `false`, where I would expect it to be `true`.

It looks like equality has not been implemented for `Url` instances, so that reference equality is being used.

**Comment by tmenier** [comment]
The [official guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/equality-operators) say "AVOID overloading equality operators on mutable reference types", which `Url` technically is. That's because equality depends on hashcodes, and if the hashcode changed when some mutable property changes (like it would here), you could run into problems if, say, you're using a `Url` as a dictionary key.

On the other hand, I would consider overriding the `Equals` method. That's oriented more toward _value_ comparisons, which is less dangerous so the rules are more lenient.

**Comment by ellenfieldn** [comment]
There's also `DO ensure that Object.Equals and the equality operators have exactly the same semantics and similar performance characteristics.` from the same link.

**Comment by ellenfieldn** [comment]
Also, as for Dictionaries, I believe that they use .GetHashCode to find which bucket the object is (or will be) in and then call .Equals() for the actual comparison. I don't believe it's accurate to say that **equality** depends on the hashcode per se.

I think the real issue is just that you cannot change a property that would cause the hash-code to change while an item is in a dictionary or hashtable.

I dunno. Equality is kinda annoying.

**Comment by hravnx** [comment]
Equality is annoying for sure. For me, this came up when using `Url`s in F# records. The built-in structural equality fails, because of this. So one way to look at it, I guess, is to just say that the `Url` class really is not suitable for that. What I've done now is implement my own immutable url type, and then just convert to `Url` where needed.

But maybe I'll experiment with what a true immutable `UrlValue` would look like in the context of Flurl. Modern .Net development seems to have the concept of a builder, that supports mutability, until a final call to some `.Build()` method, the result of which is then an immutable a value.

**Comment by tmenier** [comment]
@hravnx I think you nailed it with respect to builders. `Url` is, for all practical purposes, a builder object. (It maybe should have been named as such, but it's a little late for that.) It is mutable, and you have to `ToString` it (effively your `Build` method) in order to get something useful out of it.

So how do builders in .NET typically behave with respect to equality? Let's put it to the test:

```c#
var a = new StringBuilder("foo");
var b = new StringBuilder("foo");
```

In this case, `a == b` evaluates to `false` while `a.Equals(b)` evaluates to `true`. That's consistent with what I've read about equality of reference types: `==` is true when it's literally the same instance; `Equals` is true for 2 instances with the same "value".

How about these?

```c#
var a = new UriBuilder("http://foo.com");
var b = new UriBuilder("http://foo.com");
```

Same results as `StringBuilder`; `==` is `false` while `Equals` is true.

There are exceptions to the rule about `==` but they tend to be simple, immutable, value-y types like `String` and `Uri`. Flurl's `Url` isn't a good fit for breaking from convention in my mind.

So I'm inclined to override `Equals` but not `==`. Let me know if you have any further thoughts.

**Comment by tmenier** [comment]
Just for good measure I verified this evaluates to `false`:

```c#
new StringBuilder("foo").Equals("foo");
```

and made sure Flurl behaves the same, i.e. you can't compare a `Url` with its string representation directly.

**Comment by tmenier** [comment]
This has been released https://www.nuget.org/packages/Flurl/2.8.0

**Comment by hravnx** [comment]
I just got around to test it in F#, and it works as expected! `Flurl.Url` can now be used as record members and support `StructuralEquality`. Awesome! Thanks.
