### ISSUE TITLE
Feature Request: add a HttpCallAssertion.WithRequestUrlEncoded method

### ISSUE THREAD

**Issue by gunr2171** [tmenier/Flurl#347]
`HttpCallAssertion.WithRequestJson()` is a great method for verifying that the json data submitted to a url lines up with a given object. It pairs well with `PostJsonAsync()` (and related methods).

`HttpCallAssertion.WithRequestBody()` is great if you have a string or some custom format payload.

However, Flurl also provides support for POSTing UrlEncoded data through `PostUrlEncodedAsync`. There currently is no `WithRequest...` method that naively supports this format.

The proposal here is to add a new method to the `HttpCallAssertion` class:

```
public HttpCallAssertion WithRequestUrlEncoded(object body);
```

This would operate similar to the Json varient - where you can pass in a model and the method will verify that the Json actually sent equals the Json that should have been sent with the given model.

For now, the work-around I've been doing is manually determining what the expected Url Encoded string should be, and passing that into `WithRequestBody()`.

```
var expectedRequestBody = await (new FormUrlEncodedContent(new[]
{
	new KeyValuePair<string, string>("username", "user"),
	new KeyValuePair<string, string>("password", "pass"),
	new KeyValuePair<string, string>("grant_type", "password"),
	new KeyValuePair<string, string>("client_id", "clientid"),
	new KeyValuePair<string, string>("client_secret", "clientsecret"),
	new KeyValuePair<string, string>("scopes", "scope1 scope2")
})).ReadAsStringAsync();

httpTest.ShouldHaveCalled("http://base-url/endpoint")
	.WithVerb(HttpMethod.Post)
	.WithRequestBody(expectedRequestBody)
	.Times(1);
```

Instead of manually creating this string, I'd like to make an `object` and pass that in and let Flurl do the hard work.

**Comment by tmenier** [comment]
Seems like a good idea to me, I'll get it on the list for the next release. In the mean time, you could greatly simplify your work-around by tapping into what Flurl does provide. Have a look at the [implementation](https://github.com/tmenier/Flurl/blob/master/src/Flurl.Http/Testing/HttpCallAssertion.cs#L174-L177) of `WithRequestJson`. The new method will do exactly the same except with `GlobalSettings.UrlEncodedSerializer` instead of `JsonSerializer`. Your work-around could be an extension method that does just that.

**Comment by tmenier** [comment]
This enhancement has been [released](https://www.nuget.org/packages/Flurl.Http/2.4.0).
