### ISSUE TITLE
PostUrlEncodedAsync(object) don't work with PCL but in Console Mono

### ISSUE THREAD

**Issue by armintelker** [tmenier/Flurl#35]
Hey Todd,

When I execute a `PostUrlEncodedAsync(object)` on PCL Xamarin project
```C#
endPoint
    .AppendPathSegments("oauth", "token")
    .PostUrlEncodedAsync(new {
        username = createToken.Username,
        password = createToken.Password,
    })
    .ReceiveJson<Oauth2AccessToken>();
```
I got a empty call.RequestBody.
```C#
FlurlHttp.Configure(c => {
   ...
    c.BeforeCall = DebugUtils.LogHttpRequestCall;
   ...
});

public static class DebugUtils
{
   public static void LogHttpRequestCall(HttpCall call) 
   {
       Debug.WriteLine(
            "Request:\n" +
            "\tUrl: " + call.Url + "\n" +
            "\tHeader: " + call.Request.Headers + "\n" +
            "\tBody: " + call.RequestBody
        );
    }
}    

```

I figured out that [`data.ToKeyValuePairs()`](https://github.com/tmenier/Flurl/blob/master/Flurl.Http.Shared/Content/CapturedUrlEncodedContent.cs#L27) returns an empty `IEnumerable` and that probably [`obj.GetType().GetProperties()`](https://github.com/tmenier/Flurl/blob/master/Flurl/Util/CommonExtensions.cs#L25) don`t work correct with Xamarin PCL.

 `PostUrlEncodedAsync(IDictionary)` create a correct RequestBody.

**Comment by tmenier** [comment]
Interesting. I'm seeing several reports that Xamarin is unable to reflect on anonymous types due to how the iOS linker works. Not much I can do about that I'm afraid, but I think the work-around is to create a class with username/password public properties and use `PostUrlEncodedAsync(object)` with that instead of an anonymous object. You might also need to use the `Preserve` attribute on the type. See: http://stackoverflow.com/questions/30810180/xamarin-ios-linker-removes-members-in-class-needed-for-reflection

**Comment by tmenier** [comment]
Feel free to re-open if the work-around doesn't work and/or you know of a different solution.
