### ISSUE TITLE
Add ConfigureClient method to IFlurlClientFactory, advise using with IoC containers

### ISSUE THREAD

**Issue by tmenier** [tmenier/Flurl#356]
As demonstrated in #314, configuring `FlurlClient` in a service constructor as advised [here](https://flurl.io/docs/client-lifetime/#using-flurl-with-an-ioc-container) is not thread-safe. Add a `ConfigureClient` method to `IFlurlClientFactory` as suggested [here](https://github.com/tmenier/Flurl/issues/314#issuecomment-388053747) and document that as a better practice.

**Comment by rcollette** [comment]
On the one hand, this will avoid a concurrency exception, but it doesn't seem to provide a way to perform "one time" or "initialization" of the clients that are being created.   If the action being passed in here were only executed when the client is initially created, it would better solve (what I at least was trying to communicate as) the original problem statement.   I feel like you're so close.  I feel like you need a GetOrAdd that returns a bool and uses an out parameter (like a TryGet), and then you'll know whether the action should be called or not.

**Comment by tmenier** [comment]
@rcollette I don't believe it's the library's job to provide this. (Frankly it could be argued that the synchronization/locking in `ConfigureClient` isn't really the library's job either, but it's been there since day 1 so I don't want to take it away.) In your original issue, you're doing one-time initialization from a transient service constructor. That's the wrong place place to do it, and the docs will be updated accordingly. If you simply move your initialization code to somewhere that only gets hit once, you should be fine. There's several good options:

1. Call `FlurlHttp.ConfigureClient` at app startup.
2. Call `FlurlHttp.ConfigureClient` from a _static_ constructor in your service class (good for libraries).
3. Call `FlurlClientFactory.ConfigureClient` from during IoC registration of the factory (if using the [documented](https://flurl.io/docs/client-lifetime/#using-flurl-with-an-ioc-container) IoC pattern).

Any reason why these won't work for you?

**Comment by snekbaev** [comment]
@tmenier I was recently working on a library and it was accepting the custom "settings" class, which contained things like endpoint url, connection timeout settings, so basically I needed to configure Flurl for each setting passed. There I used if-lock-if approach. Library client app doesn't know anything about Flurl.

**Comment by tmenier** [comment]
@snekbaev Not sure where you're going with this. What's the "if" part? Ensuring initialization only happens once? If so, what if someone passes "settings" to your library a second time with updated values? That should just get ignored?

**Comment by snekbaev** [comment]
@tmenier settings are read from the db in the beginning and passed. But main idea was to hide Flurl and other library dependencies from the client app.

**Comment by tmenier** [comment]
@snekbaev Ok. I'm just trying to understand what point you're making as it relates to this issue. You would like to see Flurl provide "initialize once" functionality?

**Comment by rcollette** [comment]
To me it feels like this break encapsulation.   My transient service needs to be configured with a base URL to be able to fetch a client instance.   But now the application using my service has to also know to configure Flurl so that my service can use a client already configured by the application.

I get that the application has _some_ dependency on Flurl (.csproj and factory config) but now it seems like the application is going to have a bunch more hook points into Flurl that could otherwise be insulated from the client application, as an implementation detail of my service.

Statics generally introduce problems with testing/mocking, and I'm having trouble getting my brain to understand how static based configuration would be applied coincidentally with DI.

I can agree that that thread safety is not necessarily the responsibility of the library.   To me, it doesn't seem uncommon for libraries to provide callbacks, overrides or other extension points related to configuration of the objects/instances they create.

Perhaps I can use a ConditionalWeakTable myself, to track whether I am getting a new instance of the client in my service, and then lock and configure.  It seems like such a wee bit more of code though to provide some sort of "hook" when instances are created that would simplify use of the library.

**Comment by tmenier** [comment]
> To me it feels like this breaks encapsulation.

If configuring both a service and that service's dependencies from your IoC registration breaks encapsulation, then you could say the IoC pattern in general breaks encapsulation. This is how the pattern works - configure the whole dependency graph in one place and encapsulation is maintained throughout the _rest_ of your application. (If your service was a 3rd-party library, then yes, you'd want to hide Flurl. But I don't think that's what you're saying.)

> Statics generally introduce problems with testing/mocking

I don't think it will cause you any problems in this case, because I don't see why you'd need to fake/mock any of the config stuff. This is more akin to JSON.NET's global configuration.

I don't know a lot about your application, but to me either of these approaches feels preferable to keeping the one-time setup stuff in a constructor that gets hit a lot and building something that makes sure that logic only gets called once. To me it feels like the logic is in the wrong place. But we might have to agree to disagree on that.

**Comment by rcollette** [comment]
In my case it is a "third party" library in the sense that it is an SDK that is utilized in multiple micro-services internally.

ConditionalWeakTable will likely help me here.    Thanks for discussing.

**Comment by tmenier** [comment]
Are you going to be able to implement that without a _static_ ConditionalWeakTable? Just pointing out that statics have their place, even in a DI world. ;)

**Comment by tmenier** [comment]
This has been [released](https://www.nuget.org/packages/Flurl.Http/2.4.0).
