### ISSUE TITLE
Flurl server side equivalent

### ISSUE THREAD

**Issue by Pinox** [tmenier/Flurl#359]
Hi All,

Apologies in advance for posting a question here, but I feel the flurl users are the best to answer this.   I really like flurl on client side , is there a server side equivalent that can be recommended for use in .net core that's as easy to use as flurl for serving my api's

**Comment by tmenier** [comment]
If you're asking whether Flurl can be used server side, like in an ASP.NET Core application, absolutely. It's probably the most common use case. I don't think that's what you're asking though. If you're wondering if there's something Flurl-like for responding to HTTP calls, there isn't. It's hard to imagine what that would even look like, because they are such different programming problems. Making a client-side call is just a small task you perform as part of some larger application, and you just need a small tool to do it, like HttpClient, RestSharp, or Flurl. Responding to HTTP from the server more or less _is_ an application, and you don't need a tool, you need a framework. There are some alternatives in the .NET world, like Nancy and ServiceStack, but like ASP.NET these are big frameworks tackling a big multi-faceted problem. None of them are Flurl-like in any way.

Does that answer your question?

**Comment by Pinox** [comment]
Thanks @tmenier  , I currently use servicestack but just wanted to check if there is anything outside my radar that I'm not aware of.  thanks again.
