### ISSUE TITLE
Integers from database comes back as a long

### ISSUE THREAD

**Issue by titonton** [tmenier/Flurl#364]
I'm not exactly sure if it is the my API or Flurl but it seems like integers get converted to longs when the Flurl deserializes my dictionaries.

**Comment by tmenier** [comment]
Assuming your API returns JSON, there's no notion of `int` or `long` in JSON - only numbers. Since that's all Flurl sees, it has to guess what type you want to deserialize to C#. Defaulting non-floating point numbers to `long`s is a Json.NET behavior and [there's no way to change it](https://stackoverflow.com/questions/8297541/how-do-i-change-the-default-type-for-numeric-deserialization).

My guess is you're deserializing to a `dynamic`, right? The best fix is to create a class matching the JSON with properties typed as you want them:

```c#
public class MyType
{
    public int MyIntProperty { get; set; }
    // etc.
}
```

Then deserialize to that type instead of `dynamic`:

```c#
var result = await url.GetJsonAsync<MyType>();
```

**Comment by titonton** [comment]
That's very interesting. I was trying to deserialize to a Dctionary<string, object>. I'm assuming it still has to guess either way, which is kind of weird, considering on my REST API i explicitly return an integer if needed. Thanks man. You package rocks by the way.

**Comment by tmenier** [comment]
Thanks!

Yes, it still has to guess. Remember, even if the internals of your API specify integers, all the outside world sees is JSON, and there's nothing in that format to distinguish ints from longs. That knowledge is effectively lost when the response is serialized.
