### ISSUE TITLE
IFlurlClientFactory.Get(Url) called (at least) three times per request

### ISSUE THREAD

**Issue by matteocontrini** [tmenier/Flurl#374]
Hi,
I've found out that even when doing very basic HTTP GET requests, the FlurlClient factory is invoked multiple times, at least three from what I tried. A little example:

```csharp
FlurlHttp.Configure(settings =>
{
    settings.FlurlClientFactory = new Factory();
});

IFlurlRequest req = new FlurlRequest("https://random.org");
var resp = await req.GetAsync();
```

Where `Factory` is any factory. I used a custom one so that I could add some logging in the `Get(Url)` method.

With this very stupid and unideal implementation

```csharp
    public class Factory : IFlurlClientFactory
    {
        public virtual IFlurlClient Get(Url url)
        {
            Console.WriteLine("Client for " + url);

            return new FlurlClient();
        }

        public void Dispose()
        {
            throw new NotImplementedException();
        }
    }
```

the output is:

```
Client for https://random.org
Client for https://random.org
Client for https://random.org
```

Which doesn't really make much sense to me. I haven't looked at the source code, but I think this might produce unintended results in some cases. The factory could be implemented in a way that the returned FlurlClient is cached but not tied to or generated from the input URL, so for the same request different FlurlClient could be used during the process of building and executing the request.

It could also have a performance impact if the factory strategy is more complex than just using the hostname, for example.

Thanks for any clarification.

**Comment by tmenier** [comment]
A `FlurlClientFactory` is effectively a cache. It shouldn't matter how many times `Get` is called; it should (typically) return the same `FlurlClient` instance for the same URL. You're seeing 3 calls to `Get` because `FlurlRequest` doesn't have a hard reference to a `FlurlClient` - it gets it from the factory on the fly as needed. This is mainly because the URL tied to the request could change at any point, which could cause the request to pick a different client to use.

Specifically, the 3 times `FlurlRequest` calls `FlurlClientFactory.Get` are:
1. When its `Settings` is initialized from the client-level settings.
2. When client-level headers are merged with request-level headers.
3. When the HTTP request is actually sent.

**Comment by matteocontrini** [comment]
Thanks.

So if the factory returns a different client every time, but all of them have no default headers, I guess this behaviour actually has no downsides, right?

**Comment by tmenier** [comment]
Well, ok, I'll grant you this: if your factory creates a new instance every time _and_ sets some different headers each time, this could result in unexpected behavior. I could probably refactor and "finalize" things a bit at the point where the request is sent in order to avoid this, but honestly it's never come up because I think doing that from the factory is probably not a good idea under any circumstances, and I'm curious why you would want to, if this is indeed a real-world scenario. `FlurlClientFactory` is designed for when you don't want to manage `FlurlClient`s explicitly, and caching/reusing is almost always the way to go, especially to avoid the [infamous socket exhaustion problem](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/).

There are, however, legitimate reasons for wanting to create/dispose clients explicitly. But in this case I'd recommend doing it directly from your code rather than using a factory:

```c#
using (var cli = new FlurlClient("https://random.org"))
{
    var resp = await cli.Request("endpoint").GetAsync();
}
```

In this case the factory is bypassed and the `FlurlRequest` is "glued" to that particular `FlurlClient`. instance. In other words you have direct control over creating, (re)using, and disposing the `FlurlClient` here.

**Comment by matteocontrini** [comment]
The scenario is the one exposed in the issue about using proxies (#228). The aim is to use a different proxy for each request, so what the factory does is returning a random **cached** `FlurlClient`, each of them being associated with a custom proxy (set through `HttpClient`+`HttpClientHandler`).

I'm _not_ using different headers on each `FlurlClient`/`HttpClient`, so the only difference is the proxy associated with the client. Therefore this shouldn't be an issue, if I understand correctly the only consequence would that the proxy could change multiple times before sending the request, but it's far from being a problem. Also, since I'm doing _a lot_ of requests, creating a client each time is not an option, for the sockets problem.

I'm also aware of the DNS issues when having one singleton instance of `HttpClient`, and now that I think of it, the internal recreation of the `HttpClient` that Flurl does when the connection lease timeout expires actually throws away the proxy setting on the `HttpClient` that I pass using `new FlurlClient(client)`. This is getting increasingly complicated...

**Comment by matteocontrini** [comment]
>So does your factory create a fixed number of FlurlClients up front and round-robin them in Get?

More or less, yes. There's a fixed number of proxied `FlurlClient`s which are rotated.

>Another complication is FlurlClientFactory is a global thing, so if your app is using Flurl to call other services you'll have to account for that too.

I thought about that as well, and added a check on the URL to determine whether the request should go through the proxy or not. Therefore I have a N proxied `FlurlClient`s, and for all the other requests the default "per host" strategy is applied (one cached client per host).

>No, I don't believe that happens anywhere. Definitely not when the connection lease expires, if that's what you're referring to - a new handler will (lazily) get created there. It has to in order to solve the DNS issue.

Right, the use of `Lazy` confused me. Just to make sure I understand how it works, when I pass a custom `HttpClient` through the `FlurlClient` constructor, that client is used forever and not recreated periodically, correct? So for the DNS issue I could use the `PooledConnectionLifetime` setting introduced with .NET Core 2.1.

>If you find Flurl is fighting you too much, you might consider just wrapping the logic in some MyServiceClient class that directly creates and manages FlurlClients, HttpClients, and HttpMessageHandlers.

Thanks for the input, I'll think about that as well!

**Comment by tmenier** [comment]
> when I pass a custom `HttpClient` through the `FlurlClient` constructor, that client is used forever and not recreated periodically, correct?

Yes. Flurl's `ConnectionLeaseTimeout` setting is strictly opt-in; the default is "forever", effectively.

> So for the DNS issue I could use the `PooledConnectionLifetime` setting introduced with .NET Core 2.1.

Yes, definitely do that. Flurl's `ConnectionLeaseTimeout` exists only so there's a way to deal with the DNS problems on platforms that don't support a better way. My advice is to prefer `ServicePoint.ConnectionLeaseTimeout` if you're on full framework and `PooledConnectionLifetime` if you're on .NET Core 2.1. Frankly, they're probably better implementations than mine.

**Comment by matteocontrini** [comment]
So I went with a custom "factory" I called `FlurlClientManager`, which is very similar to the factory I previously built, but it allows me to more easily request a specific client. So I have a `GetClient(Url)` method and a `GetProxiedClient()` method. This combined with a `SocketsHttpHandler` and its `PooledConnectionLifetime` property seems to be a good solution. It avoids all the `HttpClient` problems, and it makes it easy to enable/disable the use of a proxy for each request.

I thought I would never get out of it, but if I'm not missing something this solution is good. Thank you for the assistance @tmenier!

**Comment by tmenier** [comment]
I'm actually going to keep this open and ensure that at the very least the factory `Get` is called just once from `FlurlRequest.SendAsync`. That's an easy enough change and you've convinced me that it's possible that multiple calls to a custom factory could result in something unexpected there.

**Comment by tmenier** [comment]
Your solution sounds really cool by the way. I'm wondering if sharing it via a self-answered Stack Overflow question or something like that might prove useful to others.

**Comment by matteocontrini** [comment]
@tmenier yes, [done](https://stackoverflow.com/q/52708836/1633924) :)
