### ISSUE TITLE
+ in queryString not decoded correctly

### ISSUE THREAD

**Issue by Myster** [tmenier/Flurl#41]
`+` should be decoded to space, and encoded to either `+` or `%20` but preferably `+` to keep the original encoding.  
Here is what it does:

    "?q=foo+bar".SetQueryParam("page",2).ToString()
    "?q=foo%2Bbar&page=2"

Here is what it should do:

    "?q=foo+bar".SetQueryParam("page",2).ToString()
    "?q=foo+bar&page=2"

**Comment by tmenier** [comment]
Great catch. It turns out that the method I used to decode the URL has a glitch specific to the + character, and has been blogged about by [Rick Strahl](http://weblog.west-wind.com/posts/2009/Feb/05/Html-and-Uri-String-Encoding-without-SystemWeb) and [others](http://blogs.msdn.com/b/yangxind/archive/2006/11/09/don-t-use-net-system-uri-unescapedatastring-in-url-decoding.aspx). I will provide an update soon, most likely going with Rick's method. Thanks for reporting.

**Comment by tmenier** [comment]
This is fixed almost to your liking.

1. When parsing a query string, Flurl now interprets + as a space.

2. When encoding a query string, Flurl by default encodes spaces as %20, but `Url.ToString` now optionally take an `encodeSpaceAsPlus` argument so you can control it.

The only thing you don't get here is preserving the original intent, i.e. if it goes in as a + it should come out as a +. Flurl stores unencoded values and encodes as needed, and re-architecting it to remember the original encoding seemed like a larger effort without much benefit. Severs will be perfectly happy with %20 if you're making HTTP calls, and if you want +'s for vanity you've got the `ToString` overload. Hope this a satisfactory resolution.

Both Flurl and Flurl.Http have been upgraded with this change on NuGet.

**Comment by Myster** [comment]
Sounds good :-)
