### ISSUE TITLE
Add copying constructor for Url class or chainable method

### ISSUE THREAD

**Issue by voroninp** [tmenier/Flurl#411]
Currently `Url` has default constructor and the one which accepts a `string`.

Due to implicit conversion, I can call:
```
var url = new Url("...");
var urlCopy = new Url(url);
```
However, it negatively affects performance. Sure, not critically, but still it does.

Currently I have to add same query parameter `api_token` for each API call. 

I'd like to do it this way:

```CSharp
Url baseUrl = "....".SetQueryParameter("api_token", myToken);
var getProductUrl = new Url(baseUrl)
    .AddPathSegment("products")
    .AddPathSegment(productId);
```
This option actually works, as I said above, but unnecessary parsing of a string hurts me. =)

or

```CSharp
Url baseUrl = "....".SetQueryParameter("api_token", myToken);
var getProductUrl = baseUrl.Clone()
    .AddPathSegment("products")
    .AddPathSegment(productId);
```

or

```CSharp
// any call of baseUrl returns new Url object
FrozenUrl baseUrl = "....".SetQueryParameter("api_token", myToken).AsFrozen;
var getProductUrl = baseUrl
    .AddPathSegment("products")
    .AddPathSegment(productId);
```

**Comment by tmenier** [comment]
There are patterns to do what you want more cleanly, but none that avoid string parsing at some level if that's your goal.

Whenever people want to keep some "base" URL and reuse it, I always recommend typing it as a string instead of a `Url` because via extension methods you can call all the same methods (`AppendPathSegment`, etc) but under the hood you get a new `Url` instance each time. So you're getting the cloning behavior you want without the extra noise.

In your case you want to use `SetQueryParam` on that base URL, so in this instance you do need the `ToString` "noise":

```c#
string baseUrl = "...".SetQueryParam("api_token", myToken).ToString();
```
If that's too ugly for your tests you could (gasp!) skip Flurl for this part (but still use it everywhere else):

```c#
string baseUrl = $"...?api_token={myToken}";
```
If you're using Flurl.Http, another pattern is to hold a reference to `FlurlClient` and use its `Request` method in calls to different endpoints:

```c#
var client = new FlurlClient(baseUrl.SetQueryParam("api_token", myToken));

var product = await client.Request("products", productId).GetJsonAsync<Product>();
```

Here each `FlurlRequest` gets its own copy of the base URL, which is what you want. How does that work? As you might fear, because `FlurlClient` is holding a string, not a `Url`. ;)

Look, Flurl's URL builder won't win any awards for raw performance in string manipulation. But that was never a goal, because even on the high end URLs are tiny, and going to extra lengths to avoid string parsing feels like unnecessary micro-optimization to me. We might just have to disagree on that point.

**Comment by tmenier** [comment]
I'm warming up to the idea of a `Url.Clone()` method....but it might use string parsing under the hood. ;)

**Comment by voroninp** [comment]
Provide more details, please:)

And why?

**Comment by tmenier** [comment]
Why add `Clone()`? In a word, readability. Using a string as your "starting point" instead of a `Url` is usually a very clean way to get the cloning behavior you want, but it's not very obvious. This method would be a more explicit way to do it.

**Comment by voroninp** [comment]
But I still do not get the point of parsing the string again and again instead of storing information in a structured way.:)

**Comment by tmenier** [comment]
> But I still do not get the point of parsing the string again and again instead of storing information in a structured way.:)

First, if you don't think Flurl.Url stores its information in a structured way, I invite you to take a look at the source. I think you'll change your mind.

I _could_ write `Clone` from scratch. It would just be a matter of copying a few bits of state, including the `QueryParams` collection. Although that collection uses `object`s for values instead of `string`s, mainly so that adding things like numbers and dates don't require the extra `ToString` noise. But what if someone were to use a reference type? Copying just got more complicated. Then I'd need a bunch of new unit tests to cover all the weird edge cases.

Or, I could leverage existing, well-test code and be done with it:

```c#
public Url Clone() => new Url(this);
```

I don't get the point of _not_ doing it this way. Performance? In the words of a wise man, **[It. Just. Doesn't. Matter.](https://blog.codinghorror.com/the-sad-tragedy-of-micro-optimization-theater/)**

**Comment by voroninp** [comment]
> But what if someone were to use a reference type?

Do you mean ref type for query parameter?
> Copying just got more complicated.

Why? `QueryParams` collection contains references to objects. What's the difference?

**Comment by tmenier** [comment]
The difference is that you can't simply copy the references, otherwise if you change one of those objects on `url1`, it'll be reflected on `url2`. The query params would need to be deep-copied to look out for that.

I don't want to keep debating the implementation details of something I'm not going to implement. If you want to keep posting comments here that's fine, but I'm going to move the `Clone` enhancement to a new issue because it's clearly not what you were looking for with this issue.
