### ISSUE TITLE
Can't find ETag header

### ISSUE THREAD

**Issue by wiu-wiu** [tmenier/Flurl#460]
Hello!
I didn't manage to get ETag with the help of Flurl.
Could you please help me with this issue?
After spending some time with this problem I wrote this code:
```
var uri = @"some uri";
var httpClient = new HttpClient();
var headersHttpClient = (await httpClient.GetAsync(uri)).Headers.ToString();
var headersFlurl = (await uri.GetAsync()).Headers.ToString();
```

headersHttpClient value:

> Connection: keep-alive
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> CF-RAY: 501a442609254f4e-DME
> Date: Mon, 05 Aug 2019 16:49:46 GMT
> ETag: 0
> Set-Cookie: some value here; 
> Server: cloudflare

headersFlurl value:

> Transfer-Encoding: chunked
> Connection: keep-alive
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> CF-RAY: 501a4427e82ec442-LED
> Date: Mon, 05 Aug 2019 16:49:46 GMT
> Server: cloudflare

So for some reason there is a ETag header when I use HttpClient, and no header for Flurl request.
In Flurl response I have also tried to get Headers.ETag, but this value is null.
I did configure a Flurl a little, but this is just about JSON serializing options.

So after all of this I thought that this might be a bug.

**Comment by wiu-wiu** [comment]
I've just managed to get this header.
I had to override HttpClientFactory to get it and set it with FlurlHttp.Configure method.
```
public class MyCustomHttpClientFactory : DefaultHttpClientFactory
    {
        public override HttpClient CreateHttpClient(HttpMessageHandler handler)
        {
            return new HttpClient()
            {
                // Timeouts handled per request via FlurlHttpSettings.Timeout
                Timeout = System.Threading.Timeout.InfiniteTimeSpan
            };
        }
    }
```
Default factory is using handler argument. 
And I still don't sure that my solution wouldn't harm some other parts of Flurl.

**Comment by tmenier** [comment]
Strange. Internally, Flurl just passes [whatever is returned from CreateMessageHanlder](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/Configuration/DefaultHttpClientFactory.cs#L31-L36) to the `handler` arg.

And [here's what happens when when you don't pass a handler arg to HttpClient](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L123-L126). On .NET Core at least, and I'm certain Framework is the same way.

The only real difference is Flurl sets `AutomaticDecompression` by default, but I can't imagine that's getting in the way of etags. You could test it by overriding `CreateMessageHandler` **instead**, and skip the `AutomaticDecompression` part.

What platform are you on? Any idea why your fix works?

**Comment by tmenier** [comment]
Never heard back from you. I'm not convinced there's any Flurl bug here, but if you can confirm there is with the latest 3.0 prerelease, feel free to reopen this issue.
