### ISSUE TITLE
Using Flurl in ASP.NET Core 2.2

### ISSUE THREAD

**Issue by Pyrobolser** [tmenier/Flurl#464]
Hello,

I have been reading [this blog post about Flurl](https://www.hanselman.com/blog/UsingFlurlToEasilyBuildURLsAndMakeTestableHttpClientCallsInNET.aspx).

I followed [this gist](https://gist.github.com/tmenier/d28216566a6fbf5ddc432b62c736da69?WT.mc_id=-blog-scottha) to add my configuration to _Startup.cs_ and added the _SimpleClassClient.cs_
Now I must miss something because I have no idea how to actually call _simpleClassClient.GetShows() from one of my Web API controller.

I tried to check the documentation or GitHub and StackOverflow but cannot really find a complete example.
Thank you for your help!

**Comment by tmenier** [comment]
```c#
var listOfShows = await _simpleClassClient.GetShows();
```

Does that help?

**Comment by Pyrobolser** [comment]
Sorry, I should add more info, I tried a little bit more to have this solved earlier.
My issue was that I didn't have this **_simpleClassClient** in my controller.

```csharp
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Show>>> Get()
        {
            var listOfShows= await _simpleClassClient.GetShows();
            return listOfShows;
        }
```

Where does this **_simpleClassClient** comes from ?

Right now I have some kind of homemade version where I added ``` : FlurlClient``` to the SimpleClassClient class so that it inherits FlurlClient.
I then added this piece of code in the _Startup.cs_ in _ConfigureService_.

```csharp
services.AddSingleton<IFlurlClient, SimpleClassClient>();
```

And then I am able to call the client from the controller just like I would call the database context and your piece of code become possible to put in my controller.
I am just wondering if it's the proper way to do it or if I'm wrong and doing some weird anti-pattern here.

Thanks again.

**Comment by tmenier** [comment]
I see. To be honest, I think there might be a lack of understanding of how dependency injection works. `services.Add` is for binding an interface to an implementation, allowing you to code against an interface in your controller. That interface should define what the controller can actually see and call, i.e. public methods of `SimpleCastClient`, such as `GetShows`. The whole point of that example was that Flurl could be an _implementation detail_ of `SimpleCastClient`. It's hidden, and injecting `IFlurlClient` into controllers misses the point entirely.

I'm going to close this issue because you're not reporting a bug or requesting a feature of Flurl, and this really isn't even a Flurl question at all. My advice is to not just "try things" but to learn about the pattern and understand what `ConfigureService` is actually for. Here's a good place to start:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2
