### ISSUE TITLE
Cookies are sent/received with CookiesEnabled set to false 

### ISSUE THREAD

**Issue by harnocz** [tmenier/Flurl#503]
When `CookiesEnabled` is set to `false` (on any/all `Settings` property level):

-  `FlurlRequest.Cookies` will stay empty.
- `FlurlClient.Cookies` will stay empty too.

However, the cookies in `FlurlRequest.FlurlClient.HttpMessageHandler.CookieContainer` are still getting populated given that `FlurlRequest.FlurlClient.HttpMessageHandler.UseCookies` is set to `true`. This causes cookies to be sent/received with every request through the `FlurlClient`.

**Comment by tmenier** [comment]
You are correct, and this will be addressed in 3.0 big time. I'm actually in the middle of a cookie revamp right now. Those properties never really worked right in 2.x due to the fact that `CookieContainer` can only be enabled/disabled at the handler level, and can't be changed after the first request has been sent. Flurl will offer much greater flexibility here, but it's requiring me to scrap `CookieContainer` as a backing store and completely reinvent the wheel.

**Comment by harnocz** [comment]
Is there a timeline for 3.0?

Also, let me know if there's any way to help. I'd be glad to contribute.

**Comment by tmenier** [comment]
No timeline yet. Follow @FlurlHttp on Twitter you're not, I post updates there. Also consider prereleases to be stable enough for production use, if you can live without a no-more-breaking-changes guarantee until the full release. Next prerelease will be all about cookies.

**Comment by tmenier** [comment]
@harnocz By the way, thank you for the offer to help. I don't think I need actual coding help at this point (I will keep you in mind though), but I could definitely use some people to bounce cookie ideas off of. I'll be detailing my tentative plan in a new issue, hopefully today, and will release that and [redirects](https://github.com/tmenier/Flurl/issues/500) (very closely related) in the next prerelease in the coming days.

**Comment by tmenier** [comment]
The grand plan for cookies is now posted in #506. Note that I'm considering removing the `CookiesEnabled` property entirely, please read that issue for details. If you (and others) agree with that decision, I think we can close this issue. Either way, I very much look forward to your feedback in that issue.

**Comment by tmenier** [comment]
Closing because cookies are completely revamped in 3.0, `CookiesEnabled` no longer exists, and I'm declining to fix any more cookie bugs in 2.x.

See #506. If you have a chance to upgrade to the latest prerelease and test things out, that would be great. Feel free to leave any feedback you have in that issue.
