### ISSUE TITLE
the Url lost slash after set schema 

### ISSUE THREAD

**Issue by RazgrizHsu** [tmenier/Flurl#518]
Here is UnitTest..

```
[Test]
public void SchemaError()
{
	var host = "192.168.1.1";

	var url = new Url( host );
	url.Scheme = "http";
	url.AppendPathSegment( "test1" );
	url.AppendPathSegment( "test2" );

	Assert.AreEqual( $"http://{ host }/test1/test2", url.FullPath );
}
```

And the Result
<img width="437" alt="image" src="https://user-images.githubusercontent.com/3889141/81802618-ffcc8980-9548-11ea-999d-62e75767c13c.png">

**Comment by tmenier** [comment]
Thanks for reporting. When new up a `Url`, it'll assume the string you pass is a relative path if it can't be parsed as an absolute URI. I guess you get something kind of weird when you add a scheme to that. I'll look into it and see if I can fix this without breaking other edge cases.

In the mean time, this might be a better way to express your intent:

```c#
var url = new Url("");
url.Host = "192.168.1.1";
...
```

**Comment by tmenier** [comment]
Here's what I decided with this one. When you don't pass an absolute URL to the ctor, there isn't a fool-proof way to determine whether what you did pass is a host or relative path. So I'm going to stick with assuming relative path. But as described [here](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Definition) and supported by the [examples](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Examples), the `//` is more a prefix of the authority than a suffix of the scheme. So in your case, you should technically be getting this:
```
http:192.168.1.1/test1/test2
```
rather than a single slash after `http:`. That's fixed.

I'm also adding a parmeterless constructor so in my work-around you don't have to awkwardly pass an empty string. This is nicer I think:

```c#
var url = new Url { Host = "192.168.1.1", Scheme = "http" };
```

**Comment by tmenier** [comment]
Ready in prerelease 5: https://www.nuget.org/packages/Flurl.Http/3.0.0-pre5
