### ISSUE TITLE
ParseQueryParams return 1 when the url contains no parameters

### ISSUE THREAD

**Issue by Guydraud** [tmenier/Flurl#524]
I would have expected this to return an empty collection:
`var p = Url.ParseQueryParams("http://localhost:55512/foo/bar");`

But i get this:
![sc1](https://user-images.githubusercontent.com/29076303/83511043-fffedb80-a49b-11ea-84f7-033ee812e03e.png)

**Comment by tmenier** [comment]
`ParseQueryParams` assumes the value passed is just the query, i.e. everything after the `?`, not the full URL. I would suggest this instead:

```c#
var p = new Url("http://localhost:55512/foo/bar").QueryParams;
```

**Comment by Guydraud** [comment]
I still think the contract is not clear. If `ParseQueryParams` expect a string that contains only the query, then using it like i did should throw an exception, not returning incoherent information. That being said, parsing the parameters from a complete url would be useful.

**Comment by TheTonttu** [comment]
As @Guydraud pointed out supporting complete URLs would be useful addition, and would also make sense considering current location of the method.

It seems a bit odd to have a static helper method in `Url` class that doesn't accept complete URLs. When I see `Url.ParseQueryParams` the first thing that comes to mind is that the method can be used to parse query parameters from a URL, complete or otherwise. Of course the method parameter name and comment suggest that the passed parameter should only contain the query portion but as said the method seems a bit out of place with the current behaviour.

**Comment by tmenier** [comment]
Thanks for the feedback. I do see your point, but this change would be breaking. A query string can contain pretty much anything, including a full well-formed URL, so inferring the intent is not entirely fool-proof. I'd maybe consider adding a bool to the method in order to be explicit about it. But changing the behavior as is, I know, I'm worried about people potentially getting burned by that.

**Comment by TheTonttu** [comment]
I guess it would break if someone is using URL as the first key but using URL as key, rather than the value, seems like a very strange and unintended use for queries in the first place. This shouldn't have effect if URLs are used only as the key value. Or am I missing some other edge case here?

As a side question, does the current `Url.ParseQueryParams` implementation handle some query edge case differently than `new Url(urlOrQuery).QueryParams`? Other than the URL-as-key that is.

At first glance `new Url(urlOrQuery)` also parses query strings containing URLs as key value regardless whether the query string is part of a URL or not. I realise `Url.ParseQueryParams` is used internally for parsing the query part when creating `Url` instance.

It would seem logical to move current implementation of `Url.ParseQueryParams` somewhere else, e.g. `QueryParameter` or `QueryParamCollection`, and call `new Url(urlOrQuery).QueryParams` inside `Url.ParseQueryParams`. But I guess that could also cause confusion if ParseQueryParams method in both `Url` and whatever-the-other-class-is is public.

The optional parameter seems like a reasonable compromise to minimize breaking changes. Although this could also lead to unnecessary complexity in the long run. Maybe reconsider introducing the breaking change few major releases down the road if there is going to be any major release with other restructuring changes to the API.

**Comment by tmenier** [comment]
I know I'm disagreeing with 2 different people here (red flag, right?) but I have to say I'm inclined to leave it as is. There's a whole set of static utility methods and I like that they all live on `Url`. I don't think a _static_ method on `Url` should automatically imply that the first param is a full URL. All of these take a string as their first param and that string isn't a full URL in any case:

- `ParseQueryParams`
- `ParsePathSegments`
- `Combine`
- `Encode`
- `Decode`

I know you have counter-arguments, but it's not worth introducing breaking changes even in a major version IMHO.
