### ISSUE TITLE
AddOAuthBearerToken

### ISSUE THREAD

**Issue by imtrobin** [tmenier/Flurl#529]
I realized this doesn't work

```
Url url = "url";
url.WithOAuthBearerToken (token);
ur.GetAsync ()
```
Because all the calls return a new FlurlRequest. Is that needed? I was expecting it to do like Add instead of a new object.

The reason is I'm building the url programmatically, so it's not chained together. Maybe have a AddOAuthBearerToken or have it modified original.

**Comment by tmenier** [comment]
The main reason this won't work is library separation. `Url` lives in the core Flurl library; `WithOAuthBearerToken` and `GetAsync` are extension methods that live in Flurl.Http. `Url` is little more than a specialized string builder. And conceptually, a token is not part of a URL, it's part of a request header. So in that regard I don't think it seems right to "add" a token to it, even if they were in the same library.

The more obvious way to fix your code is this:

```c#
var url = "url";
var req = url.WithOAuthBearerToken(token);
req.GetAsync();
```

But, that might be a contrived example. Maybe you're trying to avoid repeating the `WithOAuthBearerToken` call all over the place, and/or maybe you're concerned about thread safety. I might be able to recommend a better pattern but I think I'd need to see a more extended example.

**Comment by imtrobin** [comment]
Thanks, I know how to fix the bug. It's just from a usage perspective, it's a little confusing, becos SetQueryParams is build the url in same object. Then WithHeader/WithOAuthBearerToken on a url creates a new FlurlRequest, and there is similar API on FlurlRequest that adds directly

```
Url url = "ur";
FlurlRequest r = url.WithOAuthBearerToken(token);  // this creates a new FlurlRequest;
r.WithOAuthBearerToken(token);                                // this adds to existing FlurlRequest
```

I think they should be named differently to avoid confusion, like below creating two new FlurlRequest without noticing.

"ur".AppendPathSegment(..).WithOAuthBearToken (..).SetQueryParams (..).WithHeader (..)

**Comment by tmenier** [comment]
> like below creating two new FlurlRequest without noticing.

That's not correct. Only 1 `FlurlRequest` is created in your example. Extension methods on `IFlurlRequest` that mirror those on `Url` return "this".

I understand your point but this was all by design and renaming all of these would be too big of a breaking change to consider. (I'm not a fan of long method names anyway, and literally every `Url` extension method that returns a `FlurlRequest` comes with Intellisense that starts with "Creates a new FlurlRequest and...".) All extension methods are optional and there's a "long way" to do the same things, such as creating `FlurlRequest`s explicitly. That might be the better choice in your case where you're not building things fluently. The extension methods reduce keystrokes but come with the trade-off of understanding exactly what they're doing.
