### ISSUE TITLE
Null response and the cookie collection is not working properly

### ISSUE THREAD

**Issue by mincasoft** [tmenier/Flurl#537]
As mentioned in the issue #534 sometimes some requests don't get a response => `null`
From there I realized that a `NullReferenceException` error when reading cookie from response
![image](https://user-images.githubusercontent.com/42678520/88453564-5aac2680-ce92-11ea-8851-951a08160d1a.png)

Flurl.Http.FlurlHttpException: Call failed. Collection was modified; enumeration operation may not execute.
![image](https://user-images.githubusercontent.com/42678520/88453576-6e578d00-ce92-11ea-96d7-4df7893b96d6.png)

**Comment by tmenier** [comment]
The first error does sound a legitimate bug. Although I'm considering Flurl 2.x to be in maintenance mode, I might consider fixing that one.

The second is a known issue with concurrency that I don't plan on fixing. If you're doing concurrent "cookie sessions" in 2.x, my recommendation is to use a `FlurlClient` per session rather than a global singleton.

Having said all that, I would strongly recommend following #506, a complete revamp of cookies that will be released very soon in the next 3.0 prerelease. It solves these issues and much more, and I really encourage anyone using cookies with Flurl to offer feedback.

**Comment by mincasoft** [comment]
The error I encountered was reported when using Flurl version 3.0 previous 3. 
I registered the IFlurClientFactory service as Singleton with I signed up for the IFlurClientFactory service as Singleton with PerBaseRequest and EnableCookies = true

**Comment by tmenier** [comment]
None of the new cookie bits in in any of the existing prereleases yet.

**Comment by tmenier** [comment]
#506 is now released in prerelease 4. Please test and let me know if this issue is resolved.

https://www.nuget.org/packages/Flurl.Http/3.0.0-pre4

**Comment by mincasoft** [comment]
Well, thank you very much. I will test soon the problem that had previously encountered

**Comment by tmenier** [comment]
Sure thing. If you confirm it's resolved, are you ok with closing this and #520? I'd just like to clean up my list of open issues a bit by closing anything cookie-related that's a "won't fix" in 2.x and in no longer relevant in 3.0.

**Comment by tmenier** [comment]
Feel free to re-open if the latest prerelease doesn't resolve this.
