### ISSUE TITLE
HttpTest does not recognize requests while in a fixture

### ISSUE THREAD

**Issue by Hulkstance** [tmenier/Flurl#539]
I'm running tests on xunit and somehow `HttpTest` does not recognize the requests made during the test. This behavior occurs only when using fixtures. If I simply use `using var test = new HttpTest();`, it works fine.

Working code:

```csharp
[Fact]
public async Task GetData_ReturnsTrue()
{
    // Arrange
    using var test = new HttpTest();

    // Act
    await "https://stackoverflow.com".GetAsync();

    // Assert
    test
        .ShouldHaveCalled("https://stackoverflow.com")
        .WithVerb(HttpMethod.Get)
        .Times(1);
}
```

Broken code:

```csharp
public class FlurlHttpTestFixture : IDisposable
{
    public HttpTest HttpTest { get; }

    public FlurlHttpTestFixture()
    {
        HttpTest = new HttpTest();
    }

    private bool _disposed = false;

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (_disposed)
            return;

        if (disposing)
        {
            if (HttpTest != null)
                HttpTest.Dispose();
        }

        _disposed = true;
    }
}

public class FlurlTests : IClassFixture<FlurlHttpTestFixture>
{
    private readonly FlurlHttpTestFixture _fixture;

    public FlurlTests(FlurlHttpTestFixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public async Task GetData_Returns()
    {
        // Arrange
		
        // Act
        await "http://stackoverflow.com".GetAsync();

        // Assert
        _fixture.HttpTest
            .ShouldHaveCalled("http://stackoverflow.com")
            .WithVerb(HttpMethod.Get)
            .Times(1);
    }
}
```

**Comment by tmenier** [comment]
Thanks for reporting. The quickest fix is to skip the fixture pattern and just create an `HttpTest` directly in your main tests class. It's cheap to create per test so you're not gaining much by using a class fixture. But if you really want to get the bottom of why it doesn't work this way I'll lean on you a little to investigate further:

In the broken case, can you confirm that real HTTP calls are being made rather than faked? Also, just to rule it out, is it still broken with all of the disposal logic removed?

I'm not certain exactly how the XUnit framework instantiates class fixtures, but if an async boundary is crossed at any point, I can see how this would fail due to a know issue. See #375, particularly my final conclusion at the end. If that's the case, then this is more or less unfixable. To prove it out, you could write a test similar to what I did [here](https://github.com/xunit/xunit/issues/1885) except with a class fixture like yours and no `IntitializeAsync`. Basically, just take Flurl/HttpTest out of the equation and determine whether `AsyncLocal` works when provided to a class via this fixture pattern.

**Comment by Hulkstance** [comment]
You are right. When I use `using HttpTest test = new HttpTest();`, it uses fake calls. Class fixtures are making it perform the real request instead. I tried your example with class fixtures and it fails, whereas it passes without class fixtures.

**Comment by tmenier** [comment]
> I tried your example with class fixtures and it failed.

Just so I'm clear, you took Flurl out of the equation and testing using an `AsyncLocal` directly, and the value didn't stick? If so I have to assume it's related to #375 and I'll close this with a similar "won't (can't) fix".

**Comment by tmenier** [comment]
Haven't heard back. Gonna assume it's related to #375.
