### ISSUE TITLE
3.0 - Implicit cast of IFlurlResponse to HttpResponseMessage

### ISSUE THREAD

**Issue by woellij** [tmenier/Flurl#540]
Hi Guys, 
thanks for the great library.

I have a proposal to enhance the migration from 2.* to 3.0.

It would make things easier, if there was an implicit conversion from `IFlurlResponse` to `HttpResponseMessage`. That would mean though to introduce a `FlurlResponse` / `FlurResponseBase` class instead of the interface, because interfaces themself can't have implicit operators.

So statements like `HttpResponseMessage response = await someUrl.GetAsync()` won't break and would compile like before.

I'm working on a project which is having a lot of tests relying on the response-message and migrating to 3.0 would mean adjusting all tests to use flurl-request or do some other workaround.

**Comment by tmenier** [comment]
I'm a little hesitant to do that for a few reasons. `FlurlResponse` wraps the `HttpResponseMessage` and even exposes it in a property called `ResponseMessage`, so I would think transitioning would be pretty painless. Can you describe the problem in a bit more detail?

**Comment by woellij** [comment]
The pain for us lies in the 1000+ Tests that rely on a line like `HttpResponseMessage response = await someUrl.GetAsync();` and then doing assertions on the `response`.

Each line would have to be changed to either `HttpResponseMessage response = (await someUrl.GetAsync()).ResponseMessage` or through some Extension method akin to `ReceiveJson` like `ReceiveResponseMessage`:  `HttpResponseMessage response = await someUrl.GetAsync().ReceiveResponseMessage()`

I've looked for a regex to cover all cases of `SendAsync` / `{HttpVerb}Aync` to be able to replace all occurances, but failed for now and hence have put the migration to 3.0 on hold.

Maybe replacing `IFlurlResponse` with a class is a no-go thing, but together with the implicit conversion would make the migration a lot easier.

**Comment by tmenier** [comment]
Yeah sorry, hate to make it this painful.

> I've looked for a regex to cover all cases of `SendAsync` / `{HttpVerb}Async`

Since there's only a handful of verbs, maybe just take it one by one rather than trying to use a regex? Like hit all the `GetAsync`s first and if that goes well move on to the next? I'm guessing you can just sorta use the compiler errors to track your progress, which is always handy.

Another approach might be to look at what your asserts are doing after the call and focus your find & replace efforts there. FlurlResponse basically exposes all the same things as HttpResponseMessage so maybe you'd have more luck updating those lines in bulk? Just speculating here, I have no idea what your asserts actually look like.

**Comment by tmenier** [comment]
Sorry for your pains with this, but an implicit conversion just doesn't feel right here. If you're talking thousands of places I still have to think there has to be some find & replace tricks that will help here, but I can't be more specific without seeing the code. I wouldn't give up on that idea.
