### ISSUE TITLE
UrlBuilder deletes port from Url

### ISSUE THREAD

**Issue by zejtin** [tmenier/Flurl#570]
Hello, 
I've tried using Flurl Url Builder like:

`var requestUri = "https://localhost:3333".AppendPathSegment("item").AppendPathSegment(itemNumber)`

Uri gets created but without Port 3333 - `https://localhost/item/3` but I need Uri with Port

Is this intended behavior?

**Comment by tmenier** [comment]
This doesn't appear to be related to casing as mentioned in #575. I'm not sure there was ever a bug here. Are you using 3.0? Taking your example and messing around in console (with and without #575) I get these results:

```
requestUri.ToString()
"https://localhost:3333/item/3"

requestUri.ToUri().ToString()
"https://localhost:3333/item/3"

requestUri.ToString()
"https://localhost:3333/item/3"

requestUri.ToUri().ToString()
"https://localhost:3333/item/3"

requestUri.ToUri().Port
3333

requestUri.Port
3333
```

Not sure where the bug is here.

**Comment by satano** [comment]
I still believe, this is/was related to casing as in #575. Because we found that casing bug exactly this way. We had a URL with **mixed case domain and port** and we are using `AppendPathSegment(...)`. After appending the segment, the port number was gone exactly as @zejtin wrote. But I also was not able to reproduce it with the example above provided by @zejtin. When the input URL is all lowercase, everything is OK.

**Comment by zejtin** [comment]
Sorry guys somehow missed the notification :/

I used bad example URL was something like: https://dev.api.test.com:3333/Data/public/srv/v1 
so I guess the problem was that we had uppercase letter in one part

**Comment by tmenier** [comment]
@zejtin That example works fine too. Next time you report a bug, please confirm that the example you're providing is actually broken. It's a time saver. Thanks.
