### ISSUE TITLE
Configurable .configureAwait  for async calls

### ISSUE THREAD

**Issue by aprooks** [tmenier/Flurl#59]
In some environments, like Orleans and, maybe Service Fabric we cannot use `.configureAwait(false)` due to task scheduler limitations http://dotnet.github.io/orleans/Advanced-Concepts/External-Tasks-and-Grains.

This means FLurl cannot be used in Orleans, because there are `.configureAwait(false)` all over the code base

**Comment by andre-realroi** [comment]
+1

**Comment by dvs39** [comment]
+1

**Comment by aprooks** [comment]
Orleans team confirmed it is totally fine to use `.ConfigureAwait(false)` in a library code, so I'm closing the issue

**Comment by tmenier** [comment]
I'm actually breathing a small sigh of relief because I wasn't sure what to do about this. Using `ConfigureAwait(false)` everywhere was very intentional as it is widely regarded as a best practice in libraries. I didn't want to alienate Orleans devs but making ConfigureAwait configurable just felt ugly. Glad the answer sort of presented itself. :)
