### ISSUE TITLE
Drop WithClient extension methods

### ISSUE THREAD

**Issue by Richiban** [tmenier/Flurl#590]
[Original bug report]

The following code:

```csharp
async Task Main()
{
	var client = new FlurlClient("http://localhost");
	
	var result = await "/"
		.WithClient(client)
		.GetAsync();
		
	Console.WriteLine(result);
}
```

worked on v2.x but on v3 it throws the error:

```
FlurlHttpException: Call failed. An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set. GET /
```

It seems a bug was introduced where the base URL can't be set on the client any more.

**Comment by tmenier** [comment]
Thanks for reporting. This could be legitimate if the behavior changed, although I will say `WithClient` is a bit of a relic and I don't think it's used much since the `Request` method was [introduced](https://github.com/tmenier/Flurl/issues/211) in 2.0. Honestly, I kind of forgot it existed and might have considered deprecating it.

Nowadays I would recommend not doing this:

```
"/".WithClient(client)
```

and instead doing this:

```
client.Request("/")
```

**Comment by Richiban** [comment]
Thanks for the reply; we've updated our code with your suggestion.

On researching this issue when it first appeared it does seem that we're doing things a bit unusually in using the `WithClient` method. I originally discovered it only by looking at the (extension) methods available on `IFlurlRequest`.

I agree that this method should either be fixed or deprecated.

Thanks again!

**Comment by tmenier** [comment]
Note to self: consider removing WithClient in 4.0

**Comment by tmenier** [comment]
`WithClient` will be removed in the next 4.0 prerelease. I'm struggling to think of a use case where `client.Request(...)` isn't better/cleaner (or at least just as good), but if anyone has such a case feel free to describe it here. I could be persuaded to change my mind.
