### ISSUE TITLE
Custom HttpclientFactory change the verb of calls

### ISSUE THREAD

**Issue by Sethlans** [tmenier/Flurl#599]
Please provide a complete description of the bug and a code sample (or better yet, a unit test) that reproduces it.
0

I have a simple post call to an endpoint performed with Flurl. The server is always responding 500 Internal server error even if I'm expecting 200 or 404 in some cases. My code is

```
 var client = new FlurlClient
                {
                    BaseUrl = baseUrl,
                    
                };
                client.Settings.HttpClientFactory = new UntrustedCertClientFactory();
                var response = await client.Request("/myEndpoint").WithCookies(_jar).BeforeCall(BeforeCallHandler).PostJsonAsync(document);
```
When I catch the FlurlHttpException the error message is

**Call failed with status code 500 (): GET https://baseUrl/myEndpoint**

When I remove the Custom HttpClientFactory the error is

**Call failed. The SSL connection could not be established, see inner exception: POST https://baseUrl/myEndpoint**

The implementation of my HttpClientFactory is:

```
public override HttpMessageHandler CreateMessageHandler()
        {
            return new HttpClientHandler
            {
                ServerCertificateCustomValidationCallback = (a, b, c, d) => true
            };
        }
```
Why when I apply the custom HttpClientFactory the Verb in the error message is GET? it shouldn't be a POST?

**Comment by tmenier** [comment]
It's failing for a different reason. My guess is is your POST is succeeding and then it's following a redirect and failing there. You can [configure redirect behavior](https://flurl.dev/docs/configuration/#redirects) to help debug this, but I'd probably start by looking at the error response body (`FlurlHttpException.GetResponseStringAsync()`) and the `InnerException` to see if there's any clues there.

Also, what should go in those empty parentheses of the error message is the [reason phrase](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html) sent by the server. Since it's empty, the server didn't send one, which is unusual.
