### ISSUE TITLE
Can you force IPv4 instead of IPv6?

### ISSUE THREAD

**Issue by ChadJessup** [tmenier/Flurl#600]
Asked in StackOverflow: https://stackoverflow.com/questions/66215791/is-there-a-way-to-force-ipv4-requests-in-flurl-http

Wanted to ask here as well incase it turns into a documentation bug, or potential future enhancement?

I'm writing a client to a website with IP restrictions, and they only allow IPv4 IP's to be restricted against.

Is there a way to force Flurl calls to only use IPv4?

From this Answer: https://stackoverflow.com/a/37385163/1865301 It looks like an HttpWebRequest can directly be forced to allow this, but I'm not able to figure out how to do this with Flurl.

Thank you!

**Comment by tmenier** [comment]
The library doesn't address `ServicePoint` concerns directly. You should be able to get a `ServicePoint` like this:

```
var sp = ServicePointManager.FindServicePoint(uri);
```

Then set `sp.BindIPEndPointDelegate` like in the SO answer you found. Then make a call with Flurl like you normally would and see if it works. I honestly don't know if it will, I've never done anything like this, which is why I didn't answer the SO question.

**Comment by ChadJessup** [comment]
Thank you for the prompt response!

I might be missing something obvious, but I'm not sure how to associate a ```HttpWebRequest``` with a Flurl.Http call?
I see in the Flurl source where it creates a ```HttpRequestMessage``` but that seems fundamentally different from the ```HttpWebRequest``` itself from what I can see.


Only think I can think of is intercepting ```SendAsync``` on a modified ```HttpClientHandler```? Feels like I'm going down the wrong road here though...

```
protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken token)
{
    var wr = HttpWebRequest.Create("blah");
    return base.SendAsync(request, token);
}
```

**Comment by tmenier** [comment]
Flurl doesn't use HttpWebRequest at all. It uses HttpClient, and if/how those APIs use HttpWebRequest [varies from platform to platform](https://www.stevejgordon.co.uk/httpclient-connection-pooling-in-dotnet-core). The answer you linked to sets a delegate on a ServicePoint, and ServicePoints are registered globally and reused. That answer shows how to get the one you want using HttpWebRequest; my example above shows how to get it with the static ServicePointManager class. And as noted, I'm not sure if it will work.

I'm going to close this because I think it's a programming question and not even directly related to Flurl. If you reframe your SO question by asking how to do what you need using HttpClient and whatever specific platform(s) you're targeting, I can help you adapt it to Flurl. Good luck.

**Comment by ChadJessup** [comment]
Thanks! Gave me the info needed to move on, wasn't sure if there was a Flurl way to do it in general, as well if Flurl used WebRequests in any way.

I appreciate the time!
