### ISSUE TITLE
SetQueryParams when passed some collection.Cast<T>() seems to ignore cast

### ISSUE THREAD

**Issue by springy76** [tmenier/Flurl#632]
Given: `IEnumerable<int> arrayOfIntegers` (more about it further down, just wait for the WTF ; )
and `var obj = new { Filter = arrayOfIntegers };`

Test1:
`Newtonsoft.Json.JsonConvert.SerializeObject(obj)` -> "`{"Filter":[6,2]}`" (ok)
Test2:
`System.Text.Json.JsonSerializer.Serialize(obj)` -> "`{"Filter":[6,2]}`" (ok)
Test3:
`string.Join(",", obj.Filter)` -> "`6,2`" (ok)

Now Flurl:
`"http://test/api/target".SetQueryParams(obj)`
expecting:
`http://test/api/target?Filter=6&Filter=2`
but produces:
`http://test/api/target?Filter=Append&Filter=Create`

WTF?! you say? ;)

Here is the creation of arrayOfIntegers:
```
FileMode[] arrayOfCustomEnums = { FileMode.Append, FileMode.Create };
IEnumerable<int> arrayOfIntegers = arrayOfCustomEnums.Cast<int>();
```

Seems like .Cast() call is returning the very same array if the input is an array and they are somehow compatible.

Since all other kinds of serializers are able to do it the right way, and the `Filter` property is really of type `IEnumerable<int>` I think it should be possible to fix it by doing the reflection part different.

**Comment by tmenier** [comment]
Thanks, this looks legit. A quick fix on your end would be to `ToList()` the enumerable:
```
var arrayOfIntegers = arrayOfCustomEnums.Cast<int>().ToList();
```
Or:
```
var obj = new { Filter = arrayOfIntegers.ToList() };
```

**Comment by tmenier** [comment]
This one really had me stumped so I finally [posted a question about it](https://stackoverflow.com/questions/68504299/given-array-castt-how-do-i-determine-t-via-reflection). Might just have to chalk this one up as a quirk and make sure you're using the work-around.

Why does it work with those JSON serializers? I believe they are defaulting to always casting enums to integers. (They can't actually "see" the `Cast<int>` either.) That would be a breaking change in Flurl.

Why does it work with `String.Join`? Because that has an overload that specifically takes `IEnumerable<T>`. That would have to be done in several places in Flurl and I don't know that it's worth it just for this edge case.

**Comment by j2jensen** [comment]
That StackOverflow post intrigued me, so I played around with things a little.

`.SetQueryParams(new{letters = "abc".Cast<char>()})` would produce `letters=abc` instead of `letters=a&letters=b&letters=c`, right?

In theory, I think it would still be possible to address this in [one point in code](https://github.com/tmenier/Flurl/blob/e24ff982e6fdbd916864ab1e50d21507fcdae8c5/src/Flurl/Url.cs#L375) by making SetQueryParams grab the declared types of the members (rather than just key/value pairs) and, if the declared `IEnumerable<>` type doesn't match the actual type, replacing the value with a projection.
```
public object GetDeclaredTypeValues(object value, Type declaredType)
{
    if(value is IEnumerable collection && declaredType.IsGenericType 
        && declaredType.GetGenericTypeDefinition() == typeof(IEnumerable<>)
        && !collection.GetType().GetInterfaces().Contains(declaredType)
        && collection.GetType().IsAssignableTo(declaredType))
    {
        var elementType = declaredType.GetGenericArguments()[0];
        return ((IEnumerable)collection).Cast<object>().Select(element => Convert.ChangeType(element, elementType));
    }
    return value;
}
```
But I could see why you might not want to add that much complexity, when `.ToList()` or `.ToArray()` gives users a pretty straightforward workaround.

**Comment by tmenier** [comment]
@j2jensen My first reaction is that the crux of the problem is we don't know what `declaredType` is, which I think my SO question highlights.

```c#
var arrayOfIntegers = arrayOfCustomEnums.Cast<int>();
var declaredType = arrayOfIntegers.GetType(); // evaluates to FileMode[]...boo
```

But, I realized that I did myself no favors by reducing the problem. If we wrap this in an object per the original bug description, we have another avenue for reflecting on the type we need.

```c#
var obj = new { Filter = arrayOfIntegers };
var declaredType = obj.GetType().GetProperties()[0].PropertyType; // evaluates to IEnumerable<int>...yay!
```

Bottom line, I think this is fixable for this scenario:

```c#
url.SetQueryParams(new { Filter = arrayOfIntegers });
```

but probably not for this one:

```c#
url.SetQueryParam("Filter", arrayOfIntegers);
```

unless I'm still missing something. :)

**Comment by springy76** [comment]
Btw:
`Newtonsoft.Json.JsonConvert.SerializeObject(obj, new Newtonsoft.Json.Converters.StringEnumConverter())`
-> '{"Filter":["Append","Create"]}' 

but
`System.Text.Json.JsonSerializer.Serialize(obj, new System.Text.Json.JsonSerializerOptions { Converters = { new System.Text.Json.Serialization.JsonStringEnumConverter() } })`
-> '{"Filter":[6,2]}' 



I think I can live with the workaround. I btw came to the problem by using a REST API where an object has a `int? CustomIndex` property which can be used as a filter for querying. And instead of declaring multiple unrelated int-constants I declared an enum for holding all the values (the FileMode in my example).

**Comment by j2jensen** [comment]
For this one:
```
url.SetQueryParam("Filter", arrayOfIntegers);
```
It would require `SetQueryParam` to be given a generic signature, so you could figure out what type of object the caller _thought_ they were dealing with when they passed the value to you.
```
public static Url SetQueryParam<T>(this string url, string name, T value, NullValueHandling nullValueHandling = NullValueHandling.Remove) {
    var declaredType = typeof(T);
```
If you added an overload like the one above, type inference would make it so this version gets called in all cases except where the `value` is already cast to an `object`, and I don't think it would represent a breaking change.

I'm not saying you should necessarily do this: it adds a little complexity with relatively little benefit. But from an academic standpoint, it can be done with relatively few changes to the code base.

**Comment by tmenier** [comment]
Released
