### ISSUE TITLE
Support HttpMethod other than Get for DownloadFileAsync

### ISSUE THREAD

**Issue by cremor** [tmenier/Flurl#633]
I need to download a file from an API that expects the download request to be a HTTP DELETE. It seems like Flurl is hardcoded to use HTTP GET for `DownloadFileAsync`.
It would be great if Flurl would optionally accept different HTTP methods.

**Comment by tmenier** [comment]
Sorry, I'm going to decline this one as I just don't think it's a very common scenario and should be easy enough to [implement](https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/DownloadExtensions.cs#L23) as an extension method in your project. (I'm sure you can simplify the file path logic and just make it work for your scenario.) Adding a new arg that defaults to GET isn't a great option because it would have to go at the end, after the `CancellationToken`, to avoid a breaking change.
