### ISSUE TITLE
GetJsonAsync  suggest

### ISSUE THREAD

**Issue by as4234426** [tmenier/Flurl#660]
Demo：
var myClass = await "https://api.mysite.com/get".GetJsonAsync<MyClass>();

If the result is not JSON,，return null。It's not an Exception

**Comment by tmenier** [comment]
Agree to disagree. `GetJsonAsync` is a shortcut that means "get the response and deserialize the JSON because that's the format I'm expecting." If it's not what you're expecting, it's an exception, and you can use the [try/catch pattern](https://flurl.dev/docs/error-handling/) to handle it differently in exceptional cases. If you don't know what to expect, use a different method like `GetStringAsync` or just `GetAsync`. Neither "assumes" JSON format.
