### ISSUE TITLE
Reading multipart response

### ISSUE THREAD

**Issue by muhammad369** [tmenier/Flurl#661]
IFlurlResponse doesn't contain a method to read mutipart reaponse

**Comment by tmenier** [comment]
That's correct, and I'm not sure it's a good fit for the library because afaik a multipart _response_ is a very unusual thing. I've literally never seen it before. Any details about the use case? Is this a 3rd-party/public API?

**Comment by muhammad369** [comment]
I wanted to use it to read the dicom web response

https://www.dicomstandard.org/dicomweb/

**Comment by tmenier** [comment]
Ok. I'm not immediately seeing anything in these docs about multipart responses but I'll assume you're right. I looked into it a little and the solution would be quite complex to implement since HttpClient stack does not appear to have any direct support for it. Given that complexity, and that it's still a very uncommon scenario, I'm going to decline adding it.

But I think there's a way forward for you. [Here](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser) is a library that appears to have this figured out, and it's highly active and popular. I imagine you could use Flurl's `GetStreamAsync`, then use this library to process the stream, and you'd have what you need.

**Comment by muhammad369** [comment]
Yeah
I've found a solution to my case, before adding the issue
but i wanted you to implement it in the Flurl package to complete the greatness of it

Thanks for your response

**Comment by tmenier** [comment]
Yeah, there's tough calls sometimes. The high degree of complexity (or probably worse, adding a new library dependency) was sort of a deal breaker. First-class support in HttpClient that I could tap into probably would have tipped the scales in favor.
