### ISSUE TITLE
PostAsync uses increasingly much memory

### ISSUE THREAD

**Issue by mennowo** [tmenier/Flurl#686]
When using `PostAsync`/`PostMultipartAsync` and then `ReceiveJson<>`, I am seeing a gradual increase of memory usage upon repeated calls. Given this code (where FileData holds some meta data about this file):

    public async Task<MyResult> UploadFile(int objectId, FileData fileData, CancellationToken token)
    {
        try
        {
            return await _configuration.Endpoint
                .AppendPathSegments("postfile")
                .SetQueryParam("objectId", objectId)
                .WithOAuthBearerToken(AccessToken)
                .WithHeader("X-Version", "1.1")
                .PostMultipartAsync(x => x
                    .AddJson("fileData", fileData)
                    .AddFile("actualFile", fileData.FileName, contentType: "application/octet-stream", fileName: fileData.FileNameWithoutPath), token)
                .ReceiveJson<MyResult>();
        }
        catch (Exception e)
        {
            // handle
        }
    }

The memory footprint gradually increases upon making hundreds of calls. Is this normal behavior? Or am I going about this the wrong way? I am unsure how to proceed to pinpoint the actual cause of this. The same code running with a call to the `UploadFile` method uses virtually no (extra) memory. Removing the `ReceiveJson<>` part in the method has no effect.

**Comment by tmenier** [comment]
I don't think this is a bug, it's more of a programming question, which I'd prefer be posted to Stack Overflow rather than here. That said, uploading files is naturally going to consume memory, more so if you're doing them at a high rate and and especially if you're doing them concurrently. At some point you could outpace .NET's garbage collector. `AddFile` does have an optional `bufferSize` parameter, which defaults to 4096 (bytes). You could experiment with decreasing this. That, along with slowing things down and reducing concurrency, are about the only tips I can give you. Flurl is a fairly thing abstraction on top of HttpClient, so you might be able to find more tips if you search specific to that and adapt any suggestions to Flurl.

**Comment by mennowo** [comment]
Thanks for your response. I agree it is not a bug, and will post things like this on stackexchange next time. (I've grown a weary of SE after getting downvotes on thoroughly researched and carefully prepared questions, though that was not the reason to post it here.)
I'm running things on a single thread already, but will look into the bufferSize. Also I'm using an HttpClientFactory alongside Polly for communication with the API, maybe that has some influence. Anyway, thanks!
