### ISSUE TITLE
Tuple support for `ReceiveJson`

### ISSUE THREAD

**Issue by maxkoshevoi** [tmenier/Flurl#715]
API responds with JSON object with two properties. If it read them as this
```cs
request.ReceiveJson<(string A, string B)>();
```
Both `A` and `B` will be `null`. But if I read as this:

```cs
request.ReceiveJson<R>();
record R(string A, string B);
```

Both will be read successfully.

Please, add support for reading Tuples, so I'll be able to create less response objects

**Comment by tmenier** [comment]
Good idea, but not possible due to the nature of named tuples. They're more like variable names than property names in that they're squashed at compile time so serializers can't reflect on them at runtime. Your work-around of using a record is probably the closest you're going to get.

https://stackoverflow.com/questions/59103002/c-sharp-deserialize-json-into-valuetuple
