### ISSUE TITLE
PUT method passing httpcontent not working

### ISSUE THREAD

**Issue by kavehEshkofti** [tmenier/Flurl#716]
Please provide a complete description of the bug and a code sample (or better yet, a unit test) that reproduces it.
Hi, i have just noticed a PUT command passing HttpContent is not working, i added a log on the server side, the body parameters are not received, which is working correctly for POST. so i used PutJsonAsync passing them as a dynamic object and it's working. it's useful if you can fix this issue for HttpContent. thanks

**Comment by tmenier** [comment]
Please provide code that reproduces this.

**Comment by tmenier** [comment]
`PutJsonAsync` creates an `HttpContent` object, JSON-serializes the object you pass it, and sets a `Content-Type: application/json; charset=UTF-8` header. If you're doing those things yourself then it should behave the same. I'm closing this since you haven't demonstrated a bug, but if you need further help please post a question to Stack Overflow.
