### ISSUE TITLE
OnErrorAsync is not recognizing FlurlHttpTimeoutException 

### ISSUE THREAD

**Issue by es1anjlsanchez** [tmenier/Flurl#720]
We have a OnErrorAsync subscribed in every FlurlRequest. Now, I have explicitly changed the timeout to 0 in order for me to build a specific log message for timeouts. However, the object is not returning a flurlexception, but looks to be a HttpCall object only.
<img width="551" alt="image" src="https://user-images.githubusercontent.com/95854595/194872623-9b8e4d17-f1ad-4e0c-86c1-5c2f6e4079b6.png">

I tried to capture it in the code as well but no luck.
<img width="549" alt="image" src="https://user-images.githubusercontent.com/95854595/194872766-641d655b-afe7-4647-918e-364e212921b5.png">

Interestengly, if we put a try catch specifically for FlurlHttpTimeoutException, it gives the object that I was hoping to get. 
<img width="401" alt="image" src="https://user-images.githubusercontent.com/95854595/194873080-91ba158a-2546-45e9-8f47-c61be35908eb.png">

May I ask for the possible reason because I can not get any. Thanks a lot.

**Comment by tmenier** [comment]
The only thing I'm noticing in what you provided is that in your second screenshot, a `FlurlHttpTimeoutException` would get caught in the first "if" condition, because `FlurlHttpTimeoutException` inherits from ``FlurlHttpException`, hence it "is" a `FlurlHttpException`. I'm not sure if that's what you're saying is happening though. I don't think you posted enough code here to demonstrate a bug. Please show the minimal code to reproduce. And if this is not a bug but a programming question, I would encourage you to ask on Stack Overflow.

**Comment by tmenier** [comment]
Can't repro the bug as I understand it and haven't heard back with any clarifications, so closing this. Again if this is more of a programming question than I bug, please ask on Stack Overflow.
