### ISSUE TITLE
Parsing Empty List result in null instead of empty list

### ISSUE THREAD

**Issue by alexanderluettig** [tmenier/Flurl#808]
## My Code

```csharp
var response = await <url>
	.WithOAuthBearerToken(apiToken)
	.GetJsonAsync<Response>();

public class Response
{
	public List<dynamic> results;
}
```

Response JSON that i get:

```json
{
    "results" : []
}
```

## Behaviour

When running my code i exptect that the empty array will be parsed to an empty list.
In the newest version Response.results is null.

In different 3.x.x Versions Response.results is still correctly parsed to an empty list

## Things i tried

I tried different types for the List elements (Jobject, JSONObject, dynamic)
Different cases for the list property (results, Results)

**Comment by tmenier** [comment]
`dynamics` are no longer supported out of the box because STJ doesn't support them. See #699. (Also [covered](https://flurl.dev/docs/upgrade/#no-more-dynamics) in the upgrade guide.) If you need to use dynamics, switch to the [Newtonsoft serializer](https://www.nuget.org/packages/Flurl.Http.Newtonsoft), which matches 3.x behavior.

**Comment by alexanderluettig** [comment]
Ahh on thank you

**Comment by alexanderluettig** [comment]
I tested it with different types for the array and for every other type i try e.g. int, string, bool. I still get null for the parsed list

**Comment by tmenier** [comment]
Try using `GetStringAsync`, then use one of those libraries (STJ or Newtonsoft) directly to deserialize the string to the desired type. If you can get some combination to work, it should guide you on how to do it with Flurl. If not, I think at the very least you have a question you can ask on Stack Overflow that is specific to those JSON serializers and not to Flurl, exposing it to far larger audience of experts. The truth is I don't know why that specific scenario isn't working, because Flurl defers virtually all of that work to STJ or Newtonsoft, as you can tell from the dead simple implementations:

https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/Configuration/DefaultJsonSerializer.cs
https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http.Newtonsoft/NewtonsoftJsonSerializer.cs

**Comment by tmenier** [comment]
As a side-note, I would have guessed that using Newtonsoft + `List<JObject>` would have worked, but I'll take your word for it that you tried that.

**Comment by alexanderluettig** [comment]
Yeah I tried GetStringAsync in the first place.
Which gave me the json object with the empty results array. I'll try to parse the string instead.
Thanks for the help :)
