### ISSUE TITLE
Milestones and releases

### ISSUE THREAD

**Issue by kroniak** [tmenier/Flurl#81]
@tmenier  What do you think about creating milestones for Flurl and Http and correct tag releases versions? I see you dont do this.

I suffer to create milestone 2.1 for Flurl and with core RC2 release Http version 1.0.0

**Comment by tmenier** [comment]
Works for me. Milestones created, and I've started tagging releases again. (I stopped at some point. I suppose I got lazy about it, plus it wasn't very useful when it was just me.) I wasn't even aware of the release notes feature with releases. That's great - I'd been using the wiki for that but this is better. I'll probably move all past release notes there.

Flurl.Http 1.0 with has been on my mind as well. I'll go through the remaining issues and see if there's any breaking change implications, but otherwise I think it's ready.
