### ISSUE TITLE
Remove Flurl dependence in Flurl.Http

### ISSUE THREAD

**Issue by kroniak** [tmenier/Flurl#84]
When I migrated all code to cross platform build, I want to remove Flurl dependency in the Flurl.Http project and compile Flurl cs files directly in Flurl.Http.

Cross platform build is hard when changing both versions and build Flurl.Http is not possible until new version of Flurl is not available on some nuget feed.

What are you think about it?

**Comment by tmenier** [comment]
I don't completely understand the issue, but since the dependency is one way so it's always worked fine to just publish Flurl first, then pull it into Flurl.Http, test, and publish that. The advantage is that the 2 packages can take on their own life (versioned on completely independent schedules) but it's always very clear which version of Flurl that Flurl.Http currently depends on.

I like that modularity and I'd rather keep it if possible. If not, help me understand why.

**Comment by kroniak** [comment]
@tmenier OK. This was a simple question. Closed. I dont push to you. =)
