### ISSUE TITLE
Url.Combine doesn't preserve query parameters

### ISSUE THREAD

**Issue by lvermeulen** [tmenier/Flurl#95]
When using Url.Combine like so:

var url = "some_path_segment".AppendPathSegments("foo", "bar")
    .SetQueryParam("tree", "building,result,number");
var realUrl = Url.Combine(baseUrl, url);

Then the outcome is an url with the ? url-encoded, in other words the query parameters are lost.

Will submit a PR.

**Comment by tmenier** [comment]
I understand the issue but I'm going to decline the PR. The reason is that Url objects and Url.Combine are not meant to be mixed. Url.Combine is basically a string utility meant to solve one problem: ensuring that there is one and only one separator character between segments. If all you need to do is combine some root URL with one or more paths and end up with a sting, it's all you need. Url, on the other hand, is a builder object with more advanced functionality. If you're using it, you shouldn't need to use Url.Combine. In your example I'd do this:

```c#
var realUrl = baseUrl
    .AppendPathSegments("some_path_segment", "foo", "bar")
    .SetQueryParam("tree", "building,result,number");
```

Having said that, I might agree that Url.Combine shouldn't encode the query if you do something like this:

```c#
Url.Combine(baseUrl, "endpoint?foo=bar");
```

It's a little bit of a dilemma though. I think either should encode the segments you pass, or not. I'm leaning toward it not encoding the segments at all. This would be a breaking change though. I will keep this open and think on it a bit.

**Comment by lvermeulen** [comment]
@tmenier I totally understand. While you're thinking on it, allow me to provide the context for which I need this.

I am wrapping the Jenkins REST API, where for every call I combine with the base Jenkins url and send authentication and accept headers. This happens in a GetFlurlClient(url) method. Then for every API call I will do e.g.
```
var url = "job"
    .AppendPathSegments(jobName, "api", "xml")
    .SetQueryParam("tree", "building,result,number");
```
Whereupon I'd like to do a GetFlurlClient(url).DoXYZ();

It's all good if you decide to reject this - I can use my own extension method.

**Comment by tmenier** [comment]
Gotcha. Basically you want GetFlurlClient to provide the root URL and the caller to provide everything to the right of it. Flurl.Url is intended to start at the root and work strictly left to right. I see a couple ways you could make this work. One way would be to build the right side of the URL via a callback, the call would look something like this:

`GetFlurlClient(url => url.AppendPathSegment("job")...).DoXYZ();`

Another way (and the way I'd probably go with) is to just provide a global JENKINS_ROOT constant and expect caller to always build the URL off that. Could even implement your method an extension of Url and do something like this:

```c#
await JENKINS_ROOT
    .AppendPathSegments("job", jobName, "api", "xml")
    .SetQueryParam("tree", "building,result,number")
    .GetJenkinsClient()
    .DoXYZ();
```

Part of my resistance to the enhancement is that I don't want to provide too many ways to do the same thing.

**Comment by tmenier** [comment]
I've decided to close this. It's a tough call whether to change the behavior of Url.Combine but I'm going to err on the side of not introducing a breaking change. Thanks again though.

**Comment by MNF** [comment]
@tmenier, I ask you to re-consider the ability Url.Combine to support '?' and query string.
I've tried to combine 2 parts of url, the second included query string 
Url.Combine("https://api.surveymonkey.net/v3/" , "surveys?api_key=xxx");
The result "https://api.surveymonkey.net/v3/surveys/%3Fapi_key=xxx"  had encoded '?', which was unexpected for me.
I think that ability to include any parts of url, including path[?query][#fragment] is a natural expectation for Url.Combine function.
I understand that you don't want to introduce breaking change, but you can leave Combine  as is for backward compatibility and add new method, e.g. Url.CombineParts or just Combine2

**Comment by tmenier** [comment]
@MNF I would suggest this:
```c#
"https://api.surveymonkey.net/v3".AppendPathSegment("surveys").SetQueryParam("api_key", key);
```
Would that work in your case?

**Comment by MNF** [comment]
Yes, it would work, but it requires a bit more knowledge of available methods and it is longer.
Combine is the simplest and familiar method, that most of users will start from, and error, if they include query string, may disappoint them.

**Comment by tmenier** [comment]
I'm starting to be convinced.

Url.Combine is indeed simple, but that simplicity means more assumptions need to be made about intent. For instance, if you have `Url.Combine(a, b, c)`, and b has a "?" in it, do you assume it's a path segment and therefore encode the "?", or is it the beginning of the query string? Can't know for sure because it's less explicit than using `AppendPathSegment` and `SetQueryParam`. However, I'm starting to agree that it's _much_ more likely that the intent is that it's a query.

So I'll re-open this. Here's how I'm thinking this will work:
- The first "?" encountered will be interpreted as the beginning of the query. "&" becomes the separator instead of "/" for any additional parts passed.
- The first "#" encountered will be interpreted as the beginning of the fragment. No separators after that. (It would be odd to have additional parts after that, but it'll simply concat them.)
- It'll be conservative with encoding and only encode _illegal_ characters, such as spaces. It won't try to parse the value side of query params and encode them. Again, this is about assuming intent, and it'll err on the side of leaving it alone rather than risk double-encoding. If you want encoding functionality, it's a sign you should be using SetQueryParams.

Any thoughts?

**Comment by lvermeulen** [comment]
I'm in total agreement. :-)

**Comment by MNF** [comment]
Looks good for me.

**Comment by tmenier** [comment]
@lvermeulen @MNF Please test and let me know if it meets your expectations: https://www.nuget.org/packages/Flurl/2.2.0-beta1

**Comment by michael-freidgeim-webjet** [comment]
Sorry Todd, it doesn't work for my sample
        ```
//Project references  D:\Projects\MySamples\WindowsFormsRestClient\packages\Flurl.2.2.0 - beta1\lib\portable40 - net40 + sl5 + win8 + wp8 + wpa81\Flurl.dll
        private void CombinePathWithQueryStringTest()
        {
            var fullUrl = Url.Combine("https://api.surveymonkey.net/v3/", "surveys?api_key=xxx");
            Debug.WriteLine(fullUrl); //Outputs https://api.surveymonkey.net/v3/surveys%3Fapi_key=xxx
            Debug.Assert(fullUrl.Contains("?"));
        }
```

**Comment by tmenier** [comment]
Oops...it might have helped if had merged the branch with the enhancement before publishing! Sorry about that. Let's try this again:

https://www.nuget.org/packages/Flurl/2.2.0-beta2

Thanks for catching!

**Comment by michael-freidgeim-webjet** [comment]
@tmenier , it works now, thanks.
